### ISSUE TITLE
Stuck at "Loading exchange bitfinex" Version 6.0.1 in every OS 

### ISSUE THREAD

**Issue by callej1** [GuntharDeNiro/BTCT#192]
Version 6.0.1 

I have tried on windows 10 64, Win7 64 vm, Linux, and Mac and for the life of me I cant get past "Loading exchange bitfinex" if I run with the GUI or without the GUI. Firewall is off, no security things that I can see that should be preventing a connection. Tried in windows with admin rights, win7 compatibility, different pairs.... If I enter an incorrect license key I get thrown an error so its probably not license related. No settings other than debug on are set from default. 

I've enabled the debug but really cant see much in the error or out log. Will look into a wireshark but its getting to be a massive effort to install this for me and I have a day job and a two year old so if anyone can help or recommend a specific version or version, OS ect with bitfinex I'd be very appreciative .
thanks,

Erik

**Comment by uygaronur** [comment]
Same here. Tried on Windows, Ubuntu and pm2; with and without the GUI. The only output I have seen so far is this:

Loading config...
Loading exchange poloniex

**Comment by alupme** [comment]
@uygaronur Check imap_listener?

**Comment by callej1** [comment]
Thanks, I'm not using it. My understanding is it should not be set to true unless your using trading viewer right?

**Comment by uygaronur** [comment]
I've played around with all the settings, it doesn't affect the result.

**Comment by callej1** [comment]
Yeah I'm stuck as well. Went through this link.. https://gunbot.shop/how-to-fix-black-screen-after-executing-gunbot/ and thought maybe it was related to pairing and opened another thread here but that doesnt seem likely now.

**Comment by utdrmac** [comment]
yesterday, Nov 9th, Bitfinex flagged me as a USA account and closed all API access. You should log in to Bitfinex manually and see if you got similar. You may need to open a new account using a VPN (and a non-USA terminating IP) and transfer funds to the new account.

**Comment by callej1** [comment]
I'm based out of Germany so not an issue for me..

**Comment by sschleicher** [comment]
I'm having the same problem on Windows 10.  The gui runs fine, no issues there, in fact it shows charts for poloniex.  The problem I'm having is with gunthy.exe, the console says "Loading config..." followed by "Loading exchange poloniex" and nothing more.  No errors are thrown, nothing other than these messages are logged.  Trying to isolate the problem I'm running it as Administrator. I've opened up all ports for gunthy.exe.  Can anyone help?

![image](https://user-images.githubusercontent.com/6667774/32690893-62abde1c-c6c4-11e7-84a3-6cf535846892.png)

![image](https://user-images.githubusercontent.com/6667774/32690903-a98f6aec-c6c4-11e7-837e-1ce669b2a456.png)

**Comment by sschleicher** [comment]
I solved my problem after seeing the info attached in TheBotFather telegram group.  It seems that I needed to use USDT_BCH instead of USDT-BCH (underscore vs dash) even though the gui found BCH on Poloniex when I used the dash.

![image](https://user-images.githubusercontent.com/6667774/32691235-d191618a-c6c9-11e7-9e3b-a9543a30016c.png)

**Comment by uygaronur** [comment]
Same here. Check the link callej1 posted: https://gunbot.shop/how-to-fix-black-screen-after-executing-gunbot/

**Comment by sschleicher** [comment]
Not sure how to suggest an enhancement to the product but an indicator of the problem in the error window could have been very helpful.  Maybe an error that says something like:

Poloniex pair naming error!  USDT-BCH not found.  Check pair formatting rules for exchanges at https://...

**Comment by wejo13** [comment]
You have to use ETH-BTC (for exmaple) as a pair, even it signals invalid symbol

**Comment by enbirch** [comment]
I am getting the following error when running the Bitfinex exchange with ETH-BTC pair:

Loading config...
Loading exchange bitfinex
GBXT_v6.0.1 ETH-BTC Round # 1
------------------------------------------------------------------------------------------------
 ɢՍƝɮ۝Ŧ XT Edition  Scanning bitfinex for trading opportunities 2017/11/26 18:08:30
------------------------------------------------------------------------------------------------
/snapshot/gunbot-build/node_modules/lodash/lodash.js:537
      if (iteratee(array[index], index, array) === false) {
          ^

TypeError: Cannot read property 'available' of undefined
    at module.exports.Market.getBalances.Promise.bfx.wallet_balances._.forEach.pair (/snapshot/gunbot-build/bitfinex.js:0:0)
    at arrayEach (/snapshot/gunbot-build/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/snapshot/gunbot-build/node_modules/lodash/lodash.js:9359:14)
    at module.exports.Market.getBalances.Promise.bfx.wallet_balances (/snapshot/gunbot-build/bitfinex.js:0:0)
    at Request.rest.make_request.request [as _callback] (/snapshot/gunbot-build/node_modules/bitfinex-api-node/rest.js:68:12)
    at Request.init.self.callback (/snapshot/gunbot-build/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/snapshot/gunbot-build/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/snapshot/gunbot-build/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

**Comment by enbirch** [comment]
I have just updated to 6.0.2 and still getting the following issue on Ubuntu Linux when running core:

Loading config...
Loading exchange bitfinex
GBXT_v6.0.2 ETH-BTC Round # 1
------------------------------------------------------------------------------------------------
 ɢƱÑƁѺŁ XT Edition  Scanning bitfinex for trading opportunities 2017/11/27 19:11:44
------------------------------------------------------------------------------------------------
/snapshot/gunbot-build/node_modules/lodash/lodash.js:537
      if (iteratee(array[index], index, array) === false) {
          ^

TypeError: Cannot read property 'available' of undefined
    at module.exports.Market.getBalances.Promise.bfx.wallet_balances._.forEach (/snapshot/gunbot-build/bitfinex.js:0:0)
    at arrayEach (/snapshot/gunbot-build/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/snapshot/gunbot-build/node_modules/lodash/lodash.js:9359:14)
    at module.exports.Market.getBalances.Promise.bfx.wallet_balances (/snapshot/gunbot-build/bitfinex.js:0:0)
    at Request.rest.make_request.request [as _callback] (/snapshot/gunbot-build/node_modules/bitfinex-api-node/rest.js:68:12)
    at Request.init.self.callback (/snapshot/gunbot-build/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/snapshot/gunbot-build/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/snapshot/gunbot-build/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

**Comment by enbirch** [comment]
I get the same issue when running this on Windows platform also:

C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537
      if (iteratee(array[index], index, array) === false) {
          ^

TypeError: Cannot read property 'available' of undefined
    at module.exports.Market.getBalances.Promise.bfx.wallet_balances._.forEach (C:\snapshot\Gunbot-master\bitfinex.js:0:0)
    at arrayEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537:11)
    at Function.forEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:9359:14)
    at module.exports.Market.getBalances.Promise.bfx.wallet_balances (C:\snapshot\Gunbot-master\bitfinex.js:0:0)
    at Request.rest.make_request.request [as _callback] (C:\snapshot\Gunbot-master\node_modules\bitfinex-api-node\rest.js:68:12)
    at Request.init.self.callback (C:\snapshot\Gunbot-master\node_modules\request\request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\snapshot\Gunbot-master\node_modules\request\request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (C:\snapshot\Gunbot-master\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

**Comment by enbirch** [comment]
My issue seems to be with ETH pairs, I am not able to trade ETH-BTC, however, the following Ethereum pairs will work with bitfinex on 6.0.2:
IOT-ETH
OMG-ETH
EOS-ETH
BCH-ETH
NEO-ETH

As mentioned above the TradingView graphs will not work but the bot will.

**Comment by enbirch** [comment]
TypeError: Cannot read property 'available' of undefined

This error was being caused by there not being a balance available in the required trading pair on Bitfinex. In the case of BTC-USD, once i had some USD available the issue was fixed and Gunbot would continue to operate without constantly restarting.
