### ISSUE TITLE
Error parsing config? 'Cannot read property 'key' of undefined..

### ISSUE THREAD

**Issue by conanm** [GuntharDeNiro/BTCT#196]
Running gunthy-macos results in: 

`Unhandled rejection TypeError: Cannot read property 'key' of undefined
    at exchanges.map.exchange (/snapshot/gunbot/bot.lib.js:0:0)
    at Array.map (native)
    at checkLicense (/snapshot/gunbot/bot.lib.js:0:0)
    at Bot.start.loadConfig.then (/snapshot/gunbot/bot.lib.js:0:0)
    at tryCatcher (/snapshot/gunbot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.module.exports.Promise._settlePromiseFromHandler (/snapshot/gunbot/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise.module.exports.Promise._settlePromise (/snapshot/gunbot/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise.module.exports.Promise._settlePromise0 (/snapshot/gunbot/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise.module.exports.Promise._settlePromises (/snapshot/gunbot/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/snapshot/gunbot/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/snapshot/gunbot/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.__dirname.Async.drainQueues (/snapshot/gunbot/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)`

Version: v601
Commit: 928d977

Running on OSX 10.12.6 (16G29)

Config file is the one default one included in the release with my bittrex api keys pasted in. (NOTE: THERE ARE NO SPACES IN THE API KEYS).

**Comment by smzari** [comment]
I have the same problem, did you get a solution?

**Comment by conanm** [comment]
not yet

**Comment by Dante2333** [comment]
This error is related to your key in the key section, manually verify that the information on the config.js file is correct and that you are not missing any commas, this is not a bug.

TypeError: Cannot read property 'key' of undefined at
