### ISSUE TITLE
XT bug - windows

### ISSUE THREAD

**Issue by aarontayto** [GuntharDeNiro/BTCT#235]
Randomly I will get the below and Gunbot bums out, the only way to get it going again is to click "Stop" then run through the start process again;

Ping not available...
{ RequestError: Error: connect ETIMEDOUT 138.197.69.201:5000
    at new RequestError (C:\snapshot\Gunbot-master\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.module.exports.plumbing.callback (C:\snapshot\Gunbot-master\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (C:\snapshot\Gunbot-master\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.init.self.callback (C:\snapshot\Gunbot-master\node_modules\request\request.js:188:22)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Request.onRequestError (C:\snapshot\Gunbot-master\node_modules\request\request.js:884:8)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at Socket.socketErrorListener (_http_client.js:399:9)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:62:8)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
  name: 'RequestError',
  message: 'Error: connect ETIMEDOUT 138.197.69.201:5000',
  cause: 
   { Error: connect ETIMEDOUT 138.197.69.201:5000
       at Object.exports._errnoException (util.js:1026:11)
       at exports._exceptionWithHostPort (util.js:1049:20)
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)
     code: 'ETIMEDOUT',
     errno: 'ETIMEDOUT',
     syscall: 'connect',
     address: '138.197.69.201',
     port: 5000 },
  error: 
   { Error: connect ETIMEDOUT 138.197.69.201:5000
       at Object.exports._errnoException (util.js:1026:11)
       at exports._exceptionWithHostPort (util.js:1049:20)
       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:14)
     code: 'ETIMEDOUT',
     errno: 'ETIMEDOUT',
     syscall: 'connect',
     address: '138.197.69.201',
     port: 5000 },
  options: 
   { uri: 'http://api.gunthy.org:5000/ping',
     method: 'POST',
     body: '8J1Wt8byNldHdFciV4Er8ENcsmK3ikbaPi6f+4+loHq+6PKNRUUC5GGtuILEKq1LezisBltN7L1c9e4yGCYXZw==',
     headers: { 'content-type': 'text/plain' },
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false,
     transform2xxOnly: false },
  response: undefined }
[HEARTBEAT] Sending message to exchanges we are alive
[HEARTBEAT] Sending message to exchanges we are alive
[HEARTBEAT] Sending message to exchanges we are alive
[HEARTBEAT] Sending message to exchanges we are alive
[90m------------------------------------------------------------------------------------------------[39m
 [33mɢ[39m[32mƱ[39m[34mÑ[39m[35mβ[39m[31mם[39m[33mͳ[39m[90m XT Edition  Scanning poloniex for trading opportunities [39m2017/11/17 20:41:25
[90m------------------------------------------------------------------------------------------------[39m
[HEARTBEAT] Sending message to exchanges we are alive
GBXT_v6.0.1 BTC_NEOS Round # 254
[90m------------------------------------------------------------------------------------------------[39m
 [33mɢ[39m[32mƱ[39m[34mΠ[39m[35mɮ[39m[31mѺ[39m[33mŦ[39m[90m XT Edition  Scanning poloniex for trading opportunities [39m2017/11/17 20:42:27
[90m------------------------------------------------------------------------------------------------[39m
[HEARTBEAT] Sending message to exchanges we are alive
GBXT_v6.0.1 BTC_DGB Round # 254

**Comment by GuntharDeNiro** [comment]
internet drop on your connection
{ Error: connect ETIMEDOUT 138.197.69.201:5000 this is the gunthy api
[HEARTBEAT] Sending message to exchanges we are alive this is poloniex instead.
So showing your outbound is disconnected.
