### ISSUE TITLE
bug `Cannot read property '0' of undefined`

### ISSUE THREAD

**Issue by b4lthazar** [GuntharDeNiro/BTCT#258]
I noticed I was getting no trades for the past day. When I check the bot, I see this error. Restarting caused the same error.
```
/snapshot/gunbot-build/joaquin-plnx/node_modules/async/dist/async.js:2244
                task.callback.apply(task, arguments);
                              ^

TypeError: Cannot read property '0' of undefined
    at Object.module.exports.Market.returnOrderBook.poloniex.returnOrderBook [as callback] (/snapshot/gunbot-build/poloniex.js:0:0)
    at isProcessing (/snapshot/gunbot-build/joaquin-plnx/node_modules/async/dist/async.js:2244:31)
    at /snapshot/gunbot-build/joaquin-plnx/node_modules/async/dist/async.js:906:16
    at Request._callback (/snapshot/gunbot-build/joaquin-plnx/lib/index.js:136:7)
    at Request.init.self.callback (/snapshot/gunbot-build/joaquin-plnx/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/snapshot/gunbot-build/joaquin-plnx/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/snapshot/gunbot-build/joaquin-plnx/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

**Comment by b4lthazar** [comment]
nm, I fixed it. In case anyone else stumbles on here, it's because NAUT was delisted:

```
On Nov 21, 2017, the following will be delisted: SJCX, NOTE, and NAUT.Posted by SweetJohnDee at 2017-11-07 20:35:10
```
