### ISSUE TITLE
6.0.2 throw Error at Startup

### ISSUE THREAD

**Issue by oldskoolnix** [GuntharDeNiro/BTCT#290]
Fresh re-install og 6.0.2, imported configs from another bot running 6.0.2.  Has anyone seen this error before?

Please advise how I may correct this.

G:\6.0.2>gunthy.exe
pkg/prelude/bootstrap.js:1102
      throw error;
      ^

TypeError: Cannot read property 'charCodeAt' of undefined
    at C:\snapshot\Gunbot-master\crypto.lib.js:0:0
    at C:\snapshot\Gunbot-master\crypto.lib.js:0:0
    at Object.<anonymous> (C:\snapshot\Gunbot-master\crypto.lib.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1173:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at Module.require (pkg/prelude/bootstrap.js:1083:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\snapshot\Gunbot-master\bot.lib.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1173:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at Module.require (pkg/prelude/bootstrap.js:1083:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\snapshot\Gunbot-master\index.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1173:22)

**Comment by c64audio** [comment]
I've been getting this consistently from 6.0.2, even when the config file is the supplied one. I'd love to know what this is about. 6.0.1 doesn't do anything, 6.0.2 either has this error on some platforms, or suppresses buying on others, and my licence doesn't work with v5.

Utterly unusable so far :(
