### ISSUE TITLE
Gunbot keeps returning 'TypeError: Cannot read property 'NAME' of undefined

### ISSUE THREAD

**Issue by gbnoob** [GuntharDeNiro/BTCT#293]
Hi Gunbot Team,

I'm really struggling to get off to a start with Gunbot XT, v6.0.2, and Kraken (have tried half-heartedly since 3.3.2).

When running on windows and my current config, which is very basic with just one pair, XICNXETH, set up as bbsgain, keeps restarting gunthy-gui after two seconds with the below trace. When running Gunthy.exe from a command prompt, it starts over after a max of three rounds (usually two). 

Is there anything I can supply more that could help the troubleshooting?

Here is the error in full:

ɢƱҊɃõͳ XT Edition  Scanning kraken for trading opportunities 2017/12/11 09:39:11
------------------------------------------------------------------------------------------------
C:\snapshot\Gunbot-master\kraken-api\kraken.js:159
                                        return callback.call(self, null, data);
                                                        ^

TypeError: Cannot read property 'NAME' of undefined
    at module.exports.Strategy.process.Promise.try.Promise.memory.exchanges.(anonymous function).returnOrderBook (C:\snapshot\Gunbot-master\gain.js:0:0)
    at KrakenClient.module.exports.Market.returnOrderBook.setTimeout.kraken.api (C:\snapshot\Gunbot-master\kraken.js:0:0)
    at Request._callback (C:\snapshot\Gunbot-master\kraken-api\kraken.js:159:22)
    at Request.init.self.callback (C:\snapshot\Gunbot-master\kraken-api\node_modules\request\request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\snapshot\Gunbot-master\kraken-api\node_modules\request\request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (C:\snapshot\Gunbot-master\kraken-api\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
Loading config...
Loading exchange kraken

All the best,

Kristian

**Comment by gbnoob** [comment]
bbsgain is not a vaild name. Error 40 detected... Please disregard and keep on working on real issues ;-)

All the best,

Kristian
