### ISSUE TITLE
6.0.2:  Bot crashed at 2017/12/13 21:54:21 Reason: Failed to load config

### ISSUE THREAD

**Issue by oldskoolnix** [GuntharDeNiro/BTCT#297]
Hi,

Today I notice my bot appeared to be running, but the charts for each pair had disappeared.  I also discovered the following error message after restart:

Loading config...
Bot crashed at 2017/12/13 21:54:21
Reason: Failed to load config!!!
Parameter: undefined
Original error: { Error: ENOENT: no such file or directory, open 'C:\Windows\sys
tem32\config.js'
    at Object.fs.openSync (fs.js:638:18)
    at Object.fs.openSync (pkg/prelude/bootstrap.js:439:32)
    at Object.fs.readFileSync (fs.js:540:33)
    at Object.fs.readFileSync (pkg/prelude/bootstrap.js:625:36)
    at Promise (C:\snapshot\Gunbot-master\bot.lib.js:0:0)
    at Promise.module.exports.Promise._execute (C:\snapshot\Gunbot-master\node_m
odules\bluebird\js\release\debuggability.js:300:9)
    at Promise.module.exports.Promise._resolveFromExecutor (C:\snapshot\Gunbot-m
aster\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (C:\snapshot\Gunbot-master\node_modules\bluebird\js\release\p
romise.js:79:10)
    at loadConfig (C:\snapshot\Gunbot-master\bot.lib.js:0:0)
    at Object.start (C:\snapshot\Gunbot-master\bot.lib.js:0:0)
    at Object.<anonymous> (C:\snapshot\Gunbot-master\bot.lib.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1173:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at Module.require (pkg/prelude/bootstrap.js:1083:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\snapshot\Gunbot-master\index.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1173:22)
    at Object.Module._extensions..js (module.js:580:10)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Windows\\system32\\config.js' }
Loading config... 

What is this C:\\Windows\\system32\\config.js file that seems to be missing?  The only config.js I'm aware of is the one in my gunbot install directory.

Please advise

Thanks

**Comment by LKM1905** [comment]
same over here! does anyone know what to do?
