### ISSUE TITLE
7.01 Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by zrupea19** [GuntharDeNiro/BTCT#302]
I run 7.01 on windows. I adjust strategy and click "apply change". There's error as following shows.

fs.js:1053
  return binding.unlink(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, unlink 'C:\Gunbot\Gunbot.XT.Edition.-.Windows.package\Gunbot XT Edition - Windows package\*.json'
    at Object.fs.unlinkSync (fs.js:1053:18)
    at StatWatcher.fs.watchFile (C:\snapshot\Gunbot-master\bot.lib.js:0:0)
    at emitTwo (events.js:125:13)
    at StatWatcher.emit (events.js:213:7)
    at StatWatcher._handle.onchange (fs.js:1441:10)

**Comment by useR210961** [comment]
Same Error here on Linux vps. GUI and non GUI.

**Comment by useR210961** [comment]
fs.js:1053
  return binding.unlink(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, unlink '*.json'
    at Object.fs.unlinkSync (fs.js:1053:18)
    at StatWatcher.fs.watchFile (/snapshot/gunbot-build/bot.lib.js:0:0)
    at emitTwo (events.js:125:13)
    at StatWatcher.emit (events.js:213:7)
    at StatWatcher._handle.onchange (fs.js:1441:10)
fs.js:1053
  return binding.unlink(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, unlink '*.json'
    at Object.fs.unlinkSync (fs.js:1053:18)
    at StatWatcher.fs.watchFile (/snapshot/gunbot-build/bot.lib.js:0:0)
    at emitTwo (events.js:125:13)
    at StatWatcher.emit (events.js:213:7)
    at StatWatcher._handle.onchange (fs.js:1441:10)

**Comment by OnlyC** [comment]
same on Ubuntu 16.04 server. 6.0.2 still working fine.

Error: ENOENT: no such file or directory, unlink '*.json'
    at Object.fs.unlinkSync (fs.js:1053:18)
    at StatWatcher.fs.watchFile (/snapshot/gunbot-build/bot.lib.js:0:0)
    at emitTwo (events.js:125:13)
    at StatWatcher.emit (events.js:213:7)
    at StatWatcher._handle.onchange (fs.js:1441:10)
(node:12522) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Cannot read property 'replace' of undefined
(node:12522) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by useR210961** [comment]
After a fresh install and no import of old config (manually set all parameters again), it is running without errors now.
