### ISSUE TITLE
Win 7.0.1 - Error after click "Apply Changes"

### ISSUE THREAD

**Issue by XEEXCZ** [GuntharDeNiro/BTCT#307]
On click "Apply changes ", I got this error

   fs.js:1053
  return binding.unlink(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, unlink 'C:\Users\ROCKY\Desktop\GunbotXT\*.json'
    at Object.fs.unlinkSync (fs.js:1053:18)
    at StatWatcher.fs.watchFile (C:\snapshot\Gunbot-master\bot.lib.js:0:0)
    at emitTwo (events.js:125:13)
    at StatWatcher.emit (events.js:213:7)
    at StatWatcher._handle.onchange (fs.js:1441:10)

**Comment by XEEXCZ** [comment]
I don't have any dir "c:\snapshot" and file C:\snapshot\Gunbot-master\bot.lib.js on my PC

**Comment by BenAccinelli** [comment]
I get this, too

**Comment by dotpim** [comment]
Fixed in v8.
