### ISSUE TITLE
[V 7.0.1] MIN_REQUIREMENT_NOT_MET error while entering into buying cycle

### ISSUE THREAD

**Issue by thakurthakur** [GuntharDeNiro/BTCT#312]
[90m2017/12/18 19:36:08[39m: Last Bid price ETH-FCT: [42m0.05150073[49m | Last Ask: [41m0.053[49m
[90m2017/12/18 19:36:08[39m: Balance ETH: [33m3.757598[39m
[90m2017/12/18 19:36:08[39m: Balance FCT: [33m0[39m
[90m2017/12/18 19:36:08[39m: On Orders FCT: [33m0[39m
[36mProcessing strategy emotionless for ETH-FCT on bittrex[39m
BUY CYCLE
[90m2017/12/18 19:36:08[39m[36m: Entering buy cycle[39m
Error: MIN_TRADE_REQUIREMENT_NOT_MET
    at errorHandler (C:\snapshot\Gunbot-master\ctx-wrapper.js:0:0)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
GBXT_v7.0.1ETH-NEO Round # 1

**Comment by thakurthakur** [comment]
Was resolved by adjusting limit buy/sell values for strategy
