### ISSUE TITLE
[7.0.1] BUG: Binance Sell Error

### ISSUE THREAD

**Issue by agbishop** [GuntharDeNiro/BTCT#317]
I'm getting this error after it tries to sell a pair on binance:
```
original price 0.238794
original volume 0.00092
rounded price 0.238794
rounded price 0
sell order opts { symbol: 'BCCBTC',
  side: 'SELL',
  type: 'LIMIT',
  timeInForce: 'IOC',
  quantity: 0,
  price: 0.238794,
  timestamp: 1513733678.075 }
createSellOrder
SyntaxError: quantity parameters is required for this method
    at required.map (/snapshot/gunbot-build/ctx/helper/binance/binance-api.js:0:0)
    at Array.map (native)
    at checkParams (/snapshot/gunbot-build/ctx/helper/binance/binance-api.js:0:0)
    at Binance.newOrder (/snapshot/gunbot-build/ctx/helper/binance/binance-api.js:0:0)
    at module.exports.createSellOrder.Promise.loadProducts.then.resp (/snapshot/gunbot-build/ctx/js/binance.js:0:0)
    at 
    at runMicrotasksCallback (internal/process/next_tick.js:86:5)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

The sell will happen on binance but then this error will repeat after

**Comment by CarlosOlea1** [comment]
Hi
I'm having the same issue here.... can you please help!!
Thanks
