### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'masterkey' of undefined

### ISSUE THREAD

**Issue by stabenfeldt** [GuntharDeNiro/BTCT#318]
I get this error when I try to start Gunbot. I've configured Bittrex with the same key as I sent to support when I bought the license.

**Comment by dotpim** [comment]
Try the following:

1. when using the browser interface:
- enter the key and secret one time as master, one time without master

2. when using core:
- fill our your key in both the key and masterkey rows for bittrex (same for secret)

**Comment by stabenfeldt** [comment]
My config.js looks like this:
The KEY and PASS are the same.

```
1210     "exchanges": {
1211         "bittrex": {
1212             "masterkey": "KEY",
1213             "mastersecret": "PASS",
1214             "key": "KEY",
1215             "secret": "PASS"
1216         }
1217     },
```
Any other places I need to look?

**Comment by stabenfeldt** [comment]
@dotpim wrote:
> enter the key and secret one time as master, one time without master (remove keys before doing this)

I tried this from the web:
1. remove Bitrex
2. Add Bitrex key and secret with master selected.
3. Remove Bitrex and then add it again.

I guess this will give the same result as your *2.* suggestion?
Same errror as when I changed `config.js`.
I would prefer to fix it by changing config-files and code, rather than doing thing in the web. If that's possible. :-)

**Comment by dotpim** [comment]
Could you post your full config.js - with anonymized key?

**Comment by dotpim** [comment]
@stabenfeldt could you try a completely fresh install, and edit config.js to only include 1 pair and your keys? If that does not work, please report back with your full config.js

**Comment by stabenfeldt** [comment]
@dotpim That worked! 👍 
Now I get this error instead:
```
Loading the exchange - bittrex
GBXT_v7.0.1BTC-ETC Round # 1
------------------------------------------------------------------------------------------------
 ɢՍͶβʘͳ XT Edition  Scanning bittrex for trading opportunities 2017/12/21 12:30:22
------------------------------------------------------------------------------------------------
/snapshot/gunbot/node_modules/lodash/lodash.js:537
      if (iteratee(array[index], index, array) === false) {
          ^

TypeError: Cannot read property 'Available' of undefined
    at module.exports.parseBalance._.forEach (/snapshot/gunbot/ctx/js/bittrex.js:0:0)
    at arrayEach (/snapshot/gunbot/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/snapshot/gunbot/node_modules/lodash/lodash.js:9359:14)
    at Bittrex.parseBalance (/snapshot/gunbot/ctx/js/bittrex.js:0:0)
    at /snapshot/gunbot/ctx/js/bittrex.js:0:0
    at Request._callback (/snapshot/gunbot/node_modules/node-bittrex-api/node.bittrex.api.js:144:11)
    at Request.init.self.callback (/snapshot/gunbot/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/snapshot/gunbot/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/snapshot/gunbot/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

**Comment by stabenfeldt** [comment]
@dotpim Attaching config.js
[github-config.txt](https://github.com/GuntharDeNiro/BTCT/files/1579223/github-config.txt)

**Comment by dotpim** [comment]
@stabenfeldt can you try to use the emotionless section from the following link, just replace all current parameters for emotionless with the ones here: https://github.com/GuntharDeNiro/BTCT/blob/master/config.js

**Comment by stabenfeldt** [comment]
I replaced the `"strategies": {"emotionless":` section with what I found in your link.
Still same error. This is the diff:

```patch
diff --git a/config.js b/config.js
index 61116af..a23f37a 100644
--- a/config.js
+++ b/config.js
@@ -48,20 +48,26 @@
        "strategies": {
                "emotionless": {
                        "NAME": "emotionless",
-                       "TRADING_LIMIT": 0.001,
-                       "FUNDS_RESERVE": 0.001,
+                       "TRADING_LIMIT": 0.01,
+                       "FUNDS_RESERVE" : 0.001,
+                       "PERIOD": 15,
+                       "BUY_LEVEL": 0.01,
+                       "GAIN": 0.01,
+                       "EMA1": 16,
+                       "EMA2": 8,
+                       "HIGH_BB": 49,
+                       "LOW_BB": 49,
+                       "STDV": 2,
+                       "SMAPERIOD": 50,
                        "PANIC_SELL": false,
                        "DOUBLE_UP": false,
                        "DOUBLE_UP_CAP": 1,
-                       "DU_CAP_COUNT": 3,
-                       "DU_METHOD": "HIGHBB",
-                       "DU_BUYDOWN": 2,
-                       "RSI_BUY_LEVEL": 30,
-                       "OKKIES_MODE": true,
-                       "BTC_MONEY_FLOW": 35,
-                       "MIN_VOLUME_TO_BUY": 0.001,
-                       "MIN_VOLUME_TO_SELL": 0.001,
-                       "TRADES_TIMEOUT": 600
+                       "STOP_LIMIT": 60,
+                       "BUY_ENABLED": true,
+                       "MIN_VOLUME_TO_BUY": 0.0001,
+                       "MIN_VOLUME_TO_SELL": 0.0001,
+                       "TRADES_TIMEOUT": 6,
+                       "MICROTRADES" : true
```

**Comment by stabenfeldt** [comment]
Amy other suggestions? It still doesn't work.

**Comment by SlipStreams** [comment]
I have the same issue on mine but with this:
Unhandled rejection TypeError: Cannot read property 'indicators' of undefined

**Comment by SlipStreams** [comment]
I just fixed this error on my system. For me the fix was to unzip zeno gui to the gunbot folder rather than copy gunthy.exe and the config to the zeno gui folder. Not sure why that made a difference, but it did.
