### ISSUE TITLE
XT V7 errors

### ISSUE THREAD

**Issue by gazalker** [GuntharDeNiro/BTCT#324]
XT V7 runs ok for an hour or two followed by a string of errors.  ????

fs.js:1053 
  return binding.unlink(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, unlink 'C:\Users\Gazalker\Desktop\Gunbot XT V7\Gunbot XT Edition - Windows package\*.json'
    at Object.fs.unlinkSync (fs.js:1053:18)
    at StatWatcher.fs.watchFile (C:\snapshot\Gunbot-master\bot.lib.js:0:0)
    at emitTwo (events.js:125:13)
    at StatWatcher.emit (events.js:213:7)
    at StatWatcher._handle.onchange (fs.js:1441:10)
C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537
      if (iteratee(array[index], index, array) === false) {
          ^

TypeError: Cannot read property 'Available' of undefined
    at module.exports.parseBalance._.forEach (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
    at arrayEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537:11)
    at Function.forEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:9359:14)
    at Bittrex.parseBalance (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
    at C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0
    at Request._callback (C:\snapshot\Gunbot-master\node_modules\node-bittrex-api\node.bittrex.api.js:144:11)
    at Request.init.self.callback (C:\snapshot\Gunbot-master\node_modules\request\request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537
      if (iteratee(array[index], index, array) === false) {
          ^

TypeError: Cannot read property 'Available' of undefined
    at module.exports.parseBalance._.forEach (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
    at arrayEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537:11)
    at Function.forEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:9359:14)
    at Bittrex.parseBalance (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
    at C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0
    at Request._callback (C:\snapshot\Gunbot-master\node_modules\node-bittrex-api\node.bittrex.api.js:144:11)
    at Request.init.self.callback (C:\snapshot\Gunbot-master\node_modules\request\request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537
      if (iteratee(array[index], index, array) === false) {
          ^

TypeError: Cannot read property 'Available' of undefined
    at module.exports.parseBalance._.forEach (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
    at arrayEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537:11)
    at Function.forEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:9359:14)
    at Bittrex.parseBalance (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
    at C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0
    at Request._callback (C:\snapshot\Gunbot-master\node_modules\node-bittrex-api\node.bittrex.api.js:144:11)
    at Request.init.self.callback (C:\snapshot\Gunbot-master\node_modules\request\request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537
      if (iteratee(array[index], index, array) === false) {
          ^

TypeError: Cannot read property 'Available' of undefined
    at module.exports.parseBalance._.forEach (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
    at arrayEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537:11)
    at Function.forEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:9359:14)
    at Bittrex.parseBalance (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
    at C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0
    at Request._callback (C:\snapshot\Gunbot-master\node_modules\node-bittrex-api\node.bittrex.api.js:144:11)
    at Request.init.self.callback (C:\snapshot\Gunbot-master\node_modules\request\request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
(node:3924) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: APIKEY_INVALID
(node:3924) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by EDanee** [comment]
Same here:

/snapshot/gunbot-build/node_modules/lodash/lodash.js:537
      if (iteratee(array[index], index, array) === false) {
          ^

TypeError: Cannot read property 'Available' of undefined
    at module.exports.parseBalance._.forEach (/snapshot/gunbot-build/ctx/js/bittrex.js:0:0)
    at arrayEach (/snapshot/gunbot-build/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/snapshot/gunbot-build/node_modules/lodash/lodash.js:9359:14)
    at Bittrex.parseBalance (/snapshot/gunbot-build/ctx/js/bittrex.js:0:0)
    at /snapshot/gunbot-build/ctx/js/bittrex.js:0:0
    at Request._callback (/snapshot/gunbot-build/node_modules/node-bittrex-api/node.bittrex.api.js:144:11)
    at Request.init.self.callback (/snapshot/gunbot-build/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/snapshot/gunbot-build/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/snapshot/gunbot-build/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
/snapshot/gunbot-build/node_modules/lodash/lodash.js:537
      if (iteratee(array[index], index, array) === false) {
          ^

TypeError: Cannot read property 'Available' of undefined
    at module.exports.parseBalance._.forEach (/snapshot/gunbot-build/ctx/js/bittrex.js:0:0)
    at arrayEach (/snapshot/gunbot-build/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/snapshot/gunbot-build/node_modules/lodash/lodash.js:9359:14)
    at Bittrex.parseBalance (/snapshot/gunbot-build/ctx/js/bittrex.js:0:0)
    at /snapshot/gunbot-build/ctx/js/bittrex.js:0:0
    at Request._callback (/snapshot/gunbot-build/node_modules/node-bittrex-api/node.bittrex.api.js:144:11)
    at Request.init.self.callback (/snapshot/gunbot-build/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/snapshot/gunbot-build/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/snapshot/gunbot-build/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

**Comment by anouar-zh** [comment]
Same issue here

**Comment by MareG76** [comment]
C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537
      if (iteratee(array[index], index, array) === false) {
          ^

TypeError: Cannot read property 'Available' of undefined
    at module.exports.parseBalance._.forEach (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
    at arrayEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537:11)
    at Function.forEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:9359:14)
    at Bittrex.parseBalance (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
    at C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0
    at Request._callback (C:\snapshot\Gunbot-master\node_modules\node-bittrex-api\node.bittrex.api.js:144:11)
    at Request.init.self.callback (C:\snapshot\Gunbot-master\node_modules\request\request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
