### ISSUE TITLE
[7.0.2_rc2] Binance Emotionless BTC-USDT pair errors on market query

### ISSUE THREAD

**Issue by odgrim** [GuntharDeNiro/BTCT#329]
### Environment:
Existing binance account, never traded USDT on any pair.

### Steps to reproduce:
Add BTC-USDT pair to config with emotionless strat
start bot

### Result
Bot hard crashes looking for askPrice but it's undefined. 
 
# out.log
```
GBXT_v7.0.2_RC2 BTC-USDT Round # 1
------------------------------------------------------------------------------------------------
 ɢƱҊ฿øͳ XT Edition  Scanning binance for trading opportunities 2017/12/22 21:42:26
------------------------------------------------------------------------------------------------
Loading config...
Loading the exchange - binance
```

# err.log
```node
C:\snapshot\Gunbot-master\node_modules\request\request.js:188
      self._callback.apply(self, arguments)
                     ^

TypeError: Cannot read property 'askPrice' of undefined
    at Binance.parseOrderBook (C:\snapshot\Gunbot-master\ctx\js\binance.js:0:0)
    at module.exports.fetchOrderBook.Promise.binance.allBookTickers (C:\snapshot\Gunbot-master\ctx\js\binance.js:0:0)
    at Request.module.exports._makeRequest.request [as _callback] (C:\snapshot\Gunbot-master\ctx\helper\binance\binance-api.js:0:0)
    at Request.init.self.callback (C:\snapshot\Gunbot-master\node_modules\request\request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

```

if I reverse the pair for USDT-BTC

```
Loading config...
Loading the exchange - binance
GBXT_v7.0.2_RC2 USDT-BTC Round # 1
------------------------------------------------------------------------------------------------
 ɢƱƝɃםŁ XT Edition  Scanning binance for trading opportunities 2017/12/22 22:17:47
------------------------------------------------------------------------------------------------
Last trade P/L for USDT-BTC was: 0.000 %
2017/12/22 22:17:50: Entering sell cycle
WARNING: we couldnt get a BOUGHT PRICE for USDT-BTC, Please manually override it using config.js
```

**Comment by odgrim** [comment]
Yash says I'm using the wrong pair and should use USDT-BTC instead... But I really wanted to trade volatility of BTC against the USD with BTC as the primary. I guess this is a feature and not a bug.

closing at Yash's request
