### ISSUE TITLE
TypeError: Cannot read property 'Available' of undefined

### ISSUE THREAD

**Issue by crawler13** [GuntharDeNiro/BTCT#330]
Good day

Found this error while setting up gunbot XT

What causes the below issue?

Regards

TypeError: Cannot read property 'Available' of undefined
    at module.exports.parseBalance._.forEach (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
    at arrayEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537:11)
    at Function.forEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:9359:14)
    at Bittrex.parseBalance (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
    at C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0
    at Request._callback (C:\snapshot\Gunbot-master\node_modules\node-bittrex-api\node.bittrex.api.js:144:11)
    at Request.init.self.callback (C:\snapshot\Gunbot-master\node_modules\request\request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\snapshot\Gunbot-master\node_modules\request\request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (C:\snapshot\Gunbot-master\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

**Comment by kucoponi** [comment]
Hello!
I have the same problem as well, so will be glad to know what this issue is about.

**Comment by brettcallanan** [comment]
I keep getting the same error. It then shuts down the instance. Running 7.0.1 with Zeno.

**Comment by victor-stone** [comment]
I'm getting this error with 7.0.2 on aws/ec2 linux

**Comment by sloaleks** [comment]
check your pair notation. on bittrex EOS doesn't work, IOTA-MIOTA neither of both, BCN doesn't work and BCH works as BCC. I got this error as I tried to setup the offending pairs.

**Comment by ferninus** [comment]
I get the same error after 45 min to 1 hour.  All pairs stop reporting P/L, accurately and report 0.00% they also fail to recognize holdings.


      C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537

            if (iteratee(array[index], index, array) === false) {
          ^

      TypeError: Cannot read property 'Available' of undefined
          at module.exports.parseBalance._.forEach (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
          at arrayEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537:11)
          at Function.forEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:9359:14)
          at Bittrex.parseBalance (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
          at C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0
          at Request._callback (C:\snapshot\Gunbot-master\node_modules\node-bittrex-api\node.bittrex.api.js:144:11)
          at Request.init.self.callback (C:\snapshot\Gunbot-master\node_modules\request\request.js:188:22)
          at emitTwo (events.js:125:13)
          at Request.emit (events.js:213:7)
          at Request.<anonymous> (C:\snapshot\Gunbot-master\node_modules\request\request.js:1171:10)
          at emitOne (events.js:115:13)
          at Request.emit (events.js:210:7)
          at IncomingMessage.<anonymous> (C:\snapshot\Gunbot-master\node_modules\request\request.js:1091:12)
          at Object.onceWrapper (events.js:312:19)
          at emitNone (events.js:110:20)
          at IncomingMessage.emit (events.js:207:7)
          at endReadableNT (_stream_readable.js:1045:12)
          at _combinedTickCallback (internal/process/next_tick.js:102:11)
          at process._tickCallback (internal/process/next_tick.js:161:9)

**Comment by crawler13** [comment]
I went back to previous version

So fsr sr so good

**Comment by submr** [comment]
I'm having the same issue. XT 803 is running on Bittrex with two pairs and different strategies. I keep getting these messages during each cycle for each pair:

`Last trade P/L for BTC-ETH was: NaN %`

And the same for the other pair.

My bot delay is 7 .

The bot can get current bid/ask prices, the BB prices and the SMA, but the buy and sell prices remain at 0. I thought this might be because I haven't traded manually for a while so the price history would be blank or something (hence the last trade was NaN), so I added manually the override prices for both pairs: 

`
override{1} 
BOUGHT_PRICE : 0.00000 <- my actual bought price here
`

But still I'm getting this error again and again, with no trades happening:

```
TypeError: Cannot read property 'Available' of undefined
    at module.exports.parseBalance._.forEach (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
    at arrayEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537:11)
    at Function.forEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:9359:14)
    at Bittrex.parseBalance (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
    at C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0
    at Request._callback (C:\snapshot\Gunbot-master\node_modules\node-bittrex-api\node.bittrex.api.js:144:11)
    at Request.init.self.callback (C:\snapshot\Gunbot-master\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537
      if (iteratee(array[index], index, array) === false) {
          ^
```

Removing or adding the BOUGHT_PRICE override does nothing.

**Comment by submr** [comment]
Ok, I was able to get it running: I made one new manual trade for both of the currency pairs. The bot took those as a reference point, and it started doing its stuff.

**Comment by shadowbladers** [comment]
Is there anyway to get Gunther to look at this sooner?

**Comment by Steempunker** [comment]
I'm getting the same message ' TypeError: Cannot read property 'Available' of undefined' on  v8.0.3
everyday its not working i'm losing money as it doesn't trade. this should be a priority fix !!!

**Comment by shadowbladers** [comment]
I fixed this by changing BTC-QTUM to BTC-QTM which is Qtum in gunbot. Try that and see if it works then.

**Comment by BigB117** [comment]
I too get this issue with Bittrex running v8.0.3 on a Windows server.

It just loads the config and the exchange, looks at one pair and then restarts. Over and over again.

TypeError: Cannot read property 'Available' of undefined
    at module.exports.parseBalance._.forEach (/snapshot/Gunbot-master/ctx/js/bittrex.js:0:0)
    at arrayEach (/snapshot/Gunbot-master/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/snapshot/Gunbot-master/node_modules/lodash/lodash.js:9359:14)
    at Bittrex.parseBalance (/snapshot/Gunbot-master/ctx/js/bittrex.js:0:0)
    at /snapshot/Gunbot-master/ctx/js/bittrex.js:0:0
    at Request._callback (/snapshot/Gunbot-master/node_modules/node-bittrex-api/node.bittrex.api.js:144:11)
    at Request.init.self.callback (/snapshot/Gunbot-master/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/snapshot/Gunbot-master/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/snapshot/Gunbot-master/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Loading config...
Loading exchange - bittrex
GBXT_v8.0.3 USDT-BTC Round # 1
------------------------------------------------------------------------------------------------
 ɢՍͶβ๏Ł XT Edition  Scanning bittrex for trading opportunities 2018/02/22 12:50:11
------------------------------------------------------------------------------------------------

What's a working fix? Should I try an older version of Gunbot? And if so, which version is the most stable and consistent?

Thanks!

**Comment by supervixens** [comment]
Thats what Gunthar told me:
"It’s an issue with bittrex failing to provide data occasionally or when they take pairs offline for maintenance."

Makes sense, since Bittrex lags sometimes.
