### ISSUE TITLE
7.0.2 - TypeError: Cannot read property 'Available' of undefined

### ISSUE THREAD

**Issue by imastud71** [GuntharDeNiro/BTCT#335]
I received the following error on 7.0.2 after switching from 6.0.2.

C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537
      if (iteratee(array[index], index, array) === false) {
          ^

TypeError: Cannot read property 'Available' of undefined
    at module.exports.parseBalance._.forEach (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
    at arrayEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537:11)
    at Function.forEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:9359:14)
    at Bittrex.parseBalance (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
    at C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0
    at Request._callback (C:\snapshot\Gunbot-master\node_modules\node-bittrex-api\node.bittrex.api.js:144:11)
    at Request.init.self.callback (C:\snapshot\Gunbot-master\node_modules\request\request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\snapshot\Gunbot-master\node_modules\request\request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (C:\snapshot\Gunbot-master\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537
      if (iteratee(array[index], index, array) === false) {

**Comment by sloaleks** [comment]
have you checked the pair notation? it's different in 702 than in 6xx.

**Comment by r00ster** [comment]
I see this same error. I am using legitimate pairs.

**Comment by anouar-zh** [comment]
Same Issue here. Like in 7.0.1. Does this mean the bot is not working?

**Comment by lohsing** [comment]
Same issue here for me too...

**Comment by MareG76** [comment]
Same here. Happened first when I switched to 7.0.1 and still here with 7.0.2
I guess I'll use the 6.0.2 until more stable version come out.

**Comment by johanvanwambeke** [comment]
Same here. I bought a brand new bot yesterday.
It made 2 trades. I'm constantly restarting.
Keep getting these errors

**Comment by dangnm** [comment]
Same for me. This is really annoyed.

**Comment by lohsing** [comment]
To get around the issue, I downgraded to the last Version 6 bot. No errors.

**Comment by dangnm** [comment]
@lohsing  I used to use v.6.0.1 and be happy with it but Gunthar has changed something and my gunbot 6.0.1 could not work anymore and showed empty log on the terminal. I asked Gunthar and he suggested to use v7.0.2 . I wish I could use 6.0.1 again but currently it can't work anymore.

**Comment by MareG76** [comment]
On Bitcointalk I got a useful suggestion to increase Bot Delay to 5, Well it was not enough so I increased it to 7 and now the bot is working. Don't know if this is longterm solution but it is good for now.

> bitcointalk.org/index.php?topic=1715214.msg27178266#msg27178266

**Comment by MareG76** [comment]
Changing bot delay doesn't make any difference anymore, this error message is annoying. Can someone share some solution ?

**Comment by lohsing** [comment]
I downgraded to V6 and have had no error messages. Until this is resolved, I would downgrade.

**Comment by MareG76** [comment]
As of today v6.0.2 gives me same error :(

**Comment by lohsing** [comment]
Delete the entire folder and set it up from scratch again... all new pairs etc.

**Comment by dangnm** [comment]
@MareG76 I've tried your solution and it doesn't work too :( . I used to love 6.0.1, the perfect version :(

**Comment by ferninus** [comment]
Frequently have this message.  New install, new config and fresh setup.

**Comment by dangnm** [comment]
While waiting for Gunthar team to fix this issue. I have to temporarily save myself :) .  The idea is that I write a script to automatically check if the bot is alive every 2 minutes by comparing pm2 log. If the bot is dead (pm2 log doesn't change), it will restart the bot and send an email to notify you.
So if you're using Linux and pm2, this is maybe a solution for you. 
https://github.com/dangnm/pm2_log_checker
You guys can download pm2_log_checker.js , pm2_log_checker.yaml, package.json to a folder and run "npm install" , "pm2 start pm2_log_checker.yaml" after editing pm2_log_checker.js and replace app_name by your gunbot process name.

**Comment by thakurthakur** [comment]
Got same error on 7.0.2. Removed USDT pair and it worked fine. So, possible issue with USDT pairs on bittrex

**Comment by RafaelVianaCunha** [comment]
Same error in BTC pair v8.0.3  bittrex

**Comment by docAvalanche** [comment]
I just bought Gunbot and it's managed to make 2 trades in 48 hours because of this error.  It's pretty frustrating watching the charts and seeing it fail to use it's settings. I have found that some pairs are more prone to it than others, even when they are legit. ETH-NEO on bittrex is a bad one.  I'm really hoping I didn't waste my money on this thing!

**Comment by Steempunker** [comment]
I have the same error message, not even sure if its trading when this error message is up.
Are the devs doing anything to debug this?
v8.0.3

**Comment by docAvalanche** [comment]
Yeah it's super bad. I rolled back to the last v6 to get the damn thing working again. For the price you'd really hope they sort this mess out.

**Comment by shadowbladers** [comment]
We need an official answer. this is really annoying.

**Comment by stabenfeldt** [comment]
Detailed error messages saying what the app expected and why it failed,
would be tremendous helpful debugging.

**Comment by fesade** [comment]
I am using mac ,about 2 hours workin what is in err.log:

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)
/snapshot/Gunbot-master/node_modules/lodash/lodash.js:537
      if (iteratee(array[index], index, array) === false) {
          ^

TypeError: Cannot read property 'Available' of undefined
    at module.exports.parseBalance._.forEach (/snapshot/Gunbot-master/ctx/js/bittrex.js:0:0)
    at arrayEach (/snapshot/Gunbot-master/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/snapshot/Gunbot-master/node_modules/lodash/lodash.js:9359:14)
    at Bittrex.parseBalance (/snapshot/Gunbot-master/ctx/js/bittrex.js:0:0)
    at /snapshot/Gunbot-master/ctx/js/bittrex.js:0:0
    at Request._callback (/snapshot/Gunbot-master/node_modules/node-bittrex-api/node.bittrex.api.js:144:11)
    at Request.init.self.callback (/snapshot/Gunbot-master/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/snapshot/Gunbot-master/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/snapshot/Gunbot-master/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
/snapshot/Gunbot-master/node_modules/lodash/lodash.js:537
      if (iteratee(array[index], index, array) === false) {
          ^

TypeError: Cannot read property 'Available' of undefined
    at module.exports.parseBalance._.forEach (/snapshot/Gunbot-master/ctx/js/bittrex.js:0:0)
    at arrayEach (/snapshot/Gunbot-master/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/snapshot/Gunbot-master/node_modules/lodash/lodash.js:9359:14)
    at Bittrex.parseBalance (/snapshot/Gunbot-master/ctx/js/bittrex.js:0:0)
    at /snapshot/Gunbot-master/ctx/js/bittrex.js:0:0
    at Request._callback (/snapshot/Gunbot-master/node_modules/node-bittrex-api/node.bittrex.api.js:144:11)
    at Request.init.self.callback (/snapshot/Gunbot-master/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/snapshot/Gunbot-master/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/snapshot/Gunbot-master/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1024:11)
    at TCP.onread (net.js:615:25)
/snapshot/Gunbot-master/node_modules/lodash/lodash.js:537
      if (iteratee(array[index], index, array) === false) {
          ^

TypeError: Cannot read property 'Available' of undefined
    at module.exports.parseBalance._.forEach (/snapshot/Gunbot-master/ctx/js/bittrex.js:0:0)
    at arrayEach (/snapshot/Gunbot-master/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/snapshot/Gunbot-master/node_modules/lodash/lodash.js:9359:14)
    at Bittrex.parseBalance (/snapshot/Gunbot-master/ctx/js/bittrex.js:0:0)
    at /snapshot/Gunbot-master/ctx/js/bittrex.js:0:0
    at Request._callback (/snapshot/Gunbot-master/node_modules/node-bittrex-api/node.bittrex.api.js:144:11)
    at Request.init.self.callback (/snapshot/Gunbot-master/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/snapshot/Gunbot-master/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/snapshot/Gunbot-master/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
/snapshot/Gunbot-master/node_modules/lodash/lodash.js:537
      if (iteratee(array[index], index, array) === false) {
          ^

TypeError: Cannot read property 'Available' of undefined
    at module.exports.parseBalance._.forEach (/snapshot/Gunbot-master/ctx/js/bittrex.js:0:0)
    at arrayEach (/snapshot/Gunbot-master/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/snapshot/Gunbot-master/node_modules/lodash/lodash.js:9359:14)
    at Bittrex.parseBalance (/snapshot/Gunbot-master/ctx/js/bittrex.js:0:0)
    at /snapshot/Gunbot-master/ctx/js/bittrex.js:0:0
    at Request._callback (/snapshot/Gunbot-master/node_modules/node-bittrex-api/node.bittrex.api.js:144:11)
    at Request.init.self.callback (/snapshot/Gunbot-master/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/snapshot/Gunbot-master/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/snapshot/Gunbot-master/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
/snapshot/Gunbot-master/node_modules/lodash/lodash.js:537
      if (iteratee(array[index], index, array) === false) {
          ^

TypeError: Cannot read property 'Available' of undefined
    at module.exports.parseBalance._.forEach (/snapshot/Gunbot-master/ctx/js/bittrex.js:0:0)
    at arrayEach (/snapshot/Gunbot-master/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/snapshot/Gunbot-master/node_modules/lodash/lodash.js:9359:14)
    at Bittrex.parseBalance (/snapshot/Gunbot-master/ctx/js/bittrex.js:0:0)
    at /snapshot/Gunbot-master/ctx/js/bittrex.js:0:0
    at Request._callback (/snapshot/Gunbot-master/node_modules/node-bittrex-api/node.bittrex.api.js:144:11)
    at Request.init.self.callback (/snapshot/Gunbot-master/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/snapshot/Gunbot-master/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/snapshot/Gunbot-master/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)


What is my pairs ,its in attachment
![ekran resmi 2018-02-22 20 39 12](https://user-images.githubusercontent.com/32833035/36554658-ef62a776-1810-11e8-835b-b5696eb67cac.png)

ok please solve this,

**Comment by halj77** [comment]
I am getting the same errors as @fesade on GUNBOT Xt 8.0.3. on Mac. Any fix here?

**Comment by nobadysk** [comment]
I have the same errors, maybe its something with "Clear Cache" ...
I do new install, new config (no inporting old)
it worked for 2 hours, and then the first error occurred

 (C:\snapshot\Gunbot-master\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by submr** [comment]
Yeah, same here, exactly the same error. It runs a few cycles, gives that error message and reboots. I have missed several trade opportunities because of this. All of this regardless of the coin pair.
