### ISSUE TITLE
binance error

### ISSUE THREAD

**Issue by BiggieSmallsRIP** [GuntharDeNiro/BTCT#338]
Loading exchange - binance
error: fetchMyTrades
Error: Response code 400
    at Request.module.exports._makeRequest.request [as _callback] (C:\snapshot\Gunbot-master\ctx\helper\binance\binance-api.js:0:0)
    at Request.init.self.callback (C:\snapshot\Gunbot-master\node_modules\request\request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

(node:55888) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Response code 400
(node:55888) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Thibault9238** [comment]
I have almost the same error : 


Loading exchange - binance
error: fetchMyTrades
Error: Response code 400
    at Request.module.exports._makeRequest.request [as _callback] (C:\snapshot\Gunbot-master\ctx\helper\binance\binance-api.js:0:0)
    at Request.init.self.callback (C:\snapshot\Gunbot-master\node_modules\request\request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

(node:8868) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Response code 400
(node:8868) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


I can't find a solution, did anyone find one ?

**Comment by Bundfisker** [comment]
Hi,
Just bought the Gunbot. I'm having exact same error as OP.
Please advise.

Thanks

**Comment by kobkrit** [comment]
Have same issue here.

**Comment by Bundfisker** [comment]
Suddenly works here!

**Comment by maxgebhardt** [comment]
similar issue here, recurring with USDT trading:

product info: { minPrice: '0.01000000',
  maxPrice: '10000000.00000000',
  minQty: '0.00000100',
  maxQty: '10000000.00000000',
  stepSize: '0.00000100',
  minNotional: '1.00000000' }
Original price: 14770.8
Original volume: 0.02037981
Rounded price: 14770.8
Rounded volume: 0.020378999999999998
Order value: 301.01413319999995
Sell Order Opts: { symbol: 'BTCUSDT',
  side: 'SELL',
  type: 'LIMIT',
  timeInForce: 'GTC',
  quantity: 0.020378999999999998,
  price: 14770.8,
  timestamp: 1514941796276 }
error: createSellOrder
Error: Response code 400
    at Request.module.exports._makeRequest.request [as _callback] (C:\snapshot\Gunbot-master\ctx\helper\binance\binance-api.js:0:0)
    at Request.init.self.callback (C:\snapshot\Gunbot-master\node_modules\request\request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\snapshot\Gunbot-master\node_modules\request\request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (C:\snapshot\Gunbot-master\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

**Comment by pmh2017** [comment]
I have the same issue as the OP and have tried two fixes suggested in this gunthy thread (hard server reboot and resetting automatic time), with no luck so far: https://gunthy.org/forum/index.php/topic,2567.0.html

Loading config...
Loading exchange - binance
error: fetchMyTrades
Error: Response code 400
    at Request.module.exports._makeRequest.request [as _callback] (C:\snapshot\Gunbot-master\ctx\helper\binance\binance-api.js:0:0)
    at Request.init.self.callback (C:\snapshot\Gunbot-master\node_modules\request\request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

Any ideas/suggestions much appreciated!

**Comment by ecab081** [comment]
Same here.

Loading config...
Loading exchange - binance
error: fetchMyTrades
Error: Response code 400
    at Request.module.exports._makeRequest.request [as _callback] (C:\snapshot\G
unbot-master\ctx\helper\binance\binance-api.js:0:0)
    at Request.init.self.callback (C:\snapshot\Gunbot-master\node_modules\reques
t\request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (C:\snapshot\Gunbot-master\node_modules\request\reque
st.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (C:\snapshot\Gunbot-master\node_modules\reque
st\request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
(node:5736) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejec
tion id: 1): Error: Response code 400
(node:5736) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.

**Comment by loagyloag** [comment]
Same

Loading config...
Loading exchange - binance
error: fetchMyTrades
Error: Response code 401
    at Request.module.exports._makeRequest.request [as _callback] (C:\snapshot\Gunbot-master\ctx\helper\binance\binance-api.js:0:0)
    at Request.init.self.callback (C:\snapshot\Gunbot-master\node_modules\request\request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

**Comment by srfnmnk** [comment]
same

Loading config...
Loading exchange - binance
error: fetchMyTrades
Error: Response code 400
    at Request.module.exports._makeRequest.request [as _callback] (/snapshot/gunbot-build/ctx/helper/binance/binance-api.js:0:0)
    at Request.init.self.callback (/snapshot/gunbot-build/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/snapshot/gunbot-build/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/snapshot/gunbot-build/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
(node:8235) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Response code 400
(node:8235) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by macedonia21** [comment]
Same error here

Loading config...
Loading exchange - binance
error: fetchMyTrades
Error: Response code 400
    at Request.module.exports._makeRequest.request [as _callback] (/snapshot/gunbot-build/ctx/helper/binance/binance-api.js:0:0)
    at Request.init.self.callback (/snapshot/gunbot-build/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request. (/snapshot/gunbot-build/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage. (/snapshot/gunbot-build/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

Any suggestion, please?

**Comment by mobiledan121** [comment]
Are there are tow different issue here?  Some users have Response code 400 and others have Response code 401. There doesn't seem to be any other differences.  

I have checked the system time and given it several reboots without a joy. As well as checking that the pairs are correctly around the wrong way around etc

I have the 401

Loading config...
Loading exchange - binance
error: fetchMyTrades
Error: Response code 401
    at Request.module.exports._makeRequest.request [as _callback] (/snapshot/gunbot-build/ctx/helper/binance/binance-api.js:0:0)
    at Request.init.self.callback (/snapshot/gunbot-build/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request. (/snapshot/gunbot-build/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage. (/snapshot/gunbot-build/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

**Comment by mobiledan121** [comment]
I may have found a fix here
https://gunbot.shop/error-response-code-400-on-binance-how-to-fix/
For me, I had to add a second API key and up she came.

Thanks to GunbotShop

**Comment by jkreish** [comment]
Thank youuuu @mobiledan121 for sharing! Check the link above folks. Can't believe that #6 worked for me... turning off the windows system "adjust time automatically" setting and then back on again...
