### ISSUE TITLE
error on binance when i run the bot

### ISSUE THREAD

**Issue by abogandal** [GuntharDeNiro/BTCT#341]
Loading config...
Loading the exchange - binance
error: fetchMyTrades
Error: Response code 401
    at Request.module.exports._makeRequest.request [as _callback] (C:\snapshot\Gunbot-master\ctx\helper\binance\binance-api.js:0:0)
    at Request.init.self.callback (C:\snapshot\Gunbot-master\node_modules\request\request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

Errors

(node:6228) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Response code 401
(node:6228) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by nacaboose** [comment]
SAME ERROR HERE

**Comment by Dave-Cox** [comment]
Same here

**Comment by kobkrit** [comment]
I have this problem before. I wrote down the pair incorrectly. In Binance, we normally see "NEO/ETH" in the exchange website. We need to write it as "ETH-NEO".

**Comment by loagyloag** [comment]
Same here was trading ETH-TRX this morning and now all pairs spit back a 401 on the getTrades call

**Comment by mobiledan121** [comment]
I may of found a fix here
https://gunbot.shop/error-response-code-400-on-binance-how-to-fix/
I my case I had to add a second API key and up she came.

Thanks GunbotShop
