### ISSUE TITLE
TypeError: Cannot read property 'askPrice' of undefined 7.0.2

### ISSUE THREAD

**Issue by crawler13** [GuntharDeNiro/BTCT#357]
Good day

My Bittrex has not been verified for 10 days now, so I bought another license for Binance, and getting the below error

Gunbot Xmas Edition v.7.0.2
Using Binance as exchange
Getting following error
--
C:\snapshot\Gunbot-master\node_modules\request\request.js:188
      self._callback.apply(self, arguments)
                     ^

TypeError: Cannot read property 'askPrice' of undefined
    at Binance.parseOrderBook (C:\snapshot\Gunbot-master\ctx\js\binance.js:0:0)
    at module.exports.fetchOrderBook.Promise.binance.allBookTickers (C:\snapshot\Gunbot-master\ctx\js\binance.js:0:0)
    at Request.module.exports._makeRequest.request [as _callback] (C:\snapshot\Gunbot-master\ctx\helper\binance\binance-api.js:0:0)
    at Request.init.self.callback (C:\snapshot\Gunbot-master\node_modules\request\request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
C:\snapshot\Gunbot-master\node_modules\request\request.js:188
      self._callback.apply(self, arguments)
                     ^

T

**Comment by crawler13** [comment]
MY next issue:

Processing strategy bbstepgain for BTC-LTC on binance
BUY CYCLE
2017/12/29 20:56:28: Entering buy cycle
product info: { minPrice: '0.00000100',
  maxPrice: '100000.00000000',
  minQty: '0.01000000',
  maxQty: '100000.00000000',
  stepSize: '0.01000000',
  minNotional: '0.00100000' }
Original price: 0.016766
Original volume: 0.059644518668734346
Rounded price: 0.016766
Rounded volume: 0.05
Order value: 0.0008383
Error: Minimum order value must be: 0.00100000. You tried 0.0008383. Increase TRADE_LIMIT.
    at errorHandler (C:\snapshot\Gunbot-master\ctx-wrapper.js:0:0)
    at <anonymous>
GBXT_v7.0.2 BTC-LSK Round # 1
------------------------------------------------------------------------------------------------
 ɢՍҊɮ๏Ŧ XT Edition  Scanning binance for trading opportunit

**Comment by EdwardThing** [comment]
Getting the same issue.

**Comment by crawler13** [comment]
Check your pairs. Spelling and names.
