### ISSUE TITLE
Unhandled rejection StatusCodeError: 503

### ISSUE THREAD

**Issue by abertronic** [GuntharDeNiro/BTCT#371]
Hi,
Got this error while running the gunbot lite overnight. It stopped the bot and I had to sign back in.  
thanks,
Aaron

Unhandled rejection StatusCodeError: 503 - "\r\n\r\n\r\n
Service Unavailable
\r\n
HTTP Error 503. The service is unavailable.

\r\n\r\n"
    at new StatusCodeError (/snapshot/Gunbot-master/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.module.exports.plumbing.callback (/snapshot/Gunbot-master/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/snapshot/Gunbot-master/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.init.self.callback (/snapshot/Gunbot-master/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request. (/snapshot/Gunbot-master/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage. (/snapshot/Gunbot-master/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
Unhandled rejection StatusCodeError: 503 - "\r\n\r\n\r\n

**Comment by crawler13** [comment]
I am getting same error

Version 7.0.2
Bittrex
