### ISSUE TITLE
[BUG v7.0.2] TypeError: Cannot read property 'Available' of undefined

### ISSUE THREAD

**Issue by bhallouin** [GuntharDeNiro/BTCT#405]
I got the following error repeatedly which make the bot restarted :

```
   TypeError: Cannot read property 'Available' of undefined
       at module.exports.parseBalance._.forEach (/snapshot/gunbot-build/ctx/js/bittrex.js:0:0)
       at arrayEach (/snapshot/gunbot-build/node_modules/lodash/lodash.js:537:11)
       at Function.forEach (/snapshot/gunbot-build/node_modules/lodash/lodash.js:9359:14)
       at Bittrex.parseBalance (/snapshot/gunbot-build/ctx/js/bittrex.js:0:0)
       at /snapshot/gunbot-build/ctx/js/bittrex.js:0:0
       at Request._callback (/snapshot/gunbot-build/node_modules/node-bittrex-api/node.bittrex.api.js:144:11)
       at Request.init.self.callback (/snapshot/gunbot-build/node_modules/request/request.js:188:22)
       at emitTwo (events.js:125:13)
       at Request.emit (events.js:213:7)
       at Request.<anonymous> (/snapshot/gunbot-build/node_modules/request/request.js:1171:10)
       at emitOne (events.js:115:13)
       at Request.emit (events.js:210:7)
       at IncomingMessage.<anonymous> (/snapshot/gunbot-build/node_modules/request/request.js:1091:12)
       at Object.onceWrapper (events.js:312:19)
       at emitNone (events.js:110:20)
       at IncomingMessage.emit (events.js:207:7)
       at endReadableNT (_stream_readable.js:1045:12)
       at _combinedTickCallback (internal/process/next_tick.js:102:11)
       at process._tickCallback (internal/process/next_tick.js:161:9)
   /snapshot/gunbot-build/node_modules/lodash/lodash.js:537
         if (iteratee(array[index], index, array) === false) {
             ^
```

This is with Gunbot XT v7.0.2 on Ubuntu Server 16.04.3 LTS.

**Comment by yoshilee** [comment]
The same occurs here on linux debian. Without any major changes though; one instance on bittrex.
Validation of config file says good. Bot delay running on 1.

**Comment by GuntharDeNiro** [comment]
fixed in v703 thanks

**Comment by bhallouin** [comment]
@GuntharDeNiro I still got plenty of the following with version 8.0.3 now.

```
TypeError: Cannot read property 'Available' of undefined
    at module.exports.parseBalance._.forEach (/snapshot/Gunbot-master/ctx/js/bittrex.js:0:0)
    at arrayEach (/snapshot/Gunbot-master/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/snapshot/Gunbot-master/node_modules/lodash/lodash.js:9359:14)
    at Bittrex.parseBalance (/snapshot/Gunbot-master/ctx/js/bittrex.js:0:0)
    at /snapshot/Gunbot-master/ctx/js/bittrex.js:0:0
    at Request._callback (/snapshot/Gunbot-master/node_modules/node-bittrex-api/node.bittrex.api.js:144:11)
    at Request.init.self.callback (/snapshot/Gunbot-master/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/snapshot/Gunbot-master/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/snapshot/Gunbot-master/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
/snapshot/Gunbot-master/node_modules/lodash/lodash.js:537
      if (iteratee(array[index], index, array) === false) {
          ^
```

Any idea ?

**Comment by yashspatel23** [comment]
Check the pair on https://bittrex.com/status 

If it is inactive or under maintenance, then this error will appear.

**Comment by bhallouin** [comment]
Hello @yashspatel23,

Thanks for the info. but I don't think this is the root cause : as an example, I have an instance running with on BTC-ETC pair and ETC has `normal` status on Bittrex.
Same for my instance which handle OMG and POWR.

Best,

**Comment by nobadysk** [comment]
Hi, i  have instance running only  USDT-BTC, USDT-LTC   v. 8.0.3

C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537
      if (iteratee(array[index], index, array) === false) {

TypeError: Cannot read property 'Available' of undefined
    at module.exports.parseBalance._.forEach (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
    at arrayEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537:11)
    at Function.forEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:9359:14)
    at Bittrex.parseBalance (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
    at C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0
    at Request._callback (C:\snapshot\Gunbot-master\node_modules\node-bittrex-api\node.bittrex.api.js:144:11)
    at Request.init.self.callback (C:\snapshot\Gunbot-master\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by emotionlesstrader** [comment]
I get the same error :(

**Comment by supervixens** [comment]
Any news on that issue? Getting the same error, no matter I'm using windows, or ARm Version on Raspberry.

**Comment by submr** [comment]
Yeah, same here, exactly the same error. It runs a few cycles, gives that error message and reboots. I have missed several trade opportunities because of this. All of this regardless of the coin pair. Version XT 803, currently on Windows 10.
