### ISSUE TITLE
V4.0.4  -  pkg/prelude/bootstrap.js:1102       throw error;       ^ 

### ISSUE THREAD

**Issue by Cleberw3b** [GuntharDeNiro/BTCT#41]
I'm Using Mac OS 10.12.6
When gunbot starts I get this error:

Loading exchange poloniex
2017/08/17 19:56:16: Kicking poloniex, receiving new tickers...
pkg/prelude/bootstrap.js:1102
      throw error;
      ^

TypeError: Cannot read property 'indicators' of undefined
    at Object.<anonymous> (/snapshot/gunbot/tulind/index.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1173:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at Module.require (pkg/prelude/bootstrap.js:1083:31)
    at require (internal/module.js:11:18)
    at __dirname (/snapshot/gunbot/bb.js:0:0)
    at Object.<anonymous> (/snapshot/gunbot/bb.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1173:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at Module.require (pkg/prelude/bootstrap.js:1083:31)
    at require (internal/module.js:11:18)
    at module.exports (/snapshot/gunbot/requirefix.js:0:0)
    at Timeout._.forEach._.forEach.Promise.then.setTimeout [as _onTimeout] (/snapshot/gunbot/bot.js:0:0)
    at ontimeout (timers.js:488:11)

**Comment by Cleberw3b** [comment]
Noob first attempt...
Must start from terminal.
