### ISSUE TITLE
Tradingview IMAP not working with Office 365 email service

### ISSUE THREAD

**Issue by zafari27** [GuntharDeNiro/BTCT#424]
Please can you check why gunbot doesnt like talking to office 365 imap services.
I have setup and tested my office 365 mail service with an app password & a normal password via a 3rd party imap client which works 100%.

Gunbot doesnt like the setup and throws these errors.

---snippet of log---
2018/01/12 14:21:36 Checking for new emails ɢՍŋβ๏ͳ v7.0.2 TRADINGVIEW Edition
Fetch error: Error: Command Error. 10
2018/01/12 14:21:36 Done fetching all messages!
{ Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:848:14)
  code: 'EPIPE',
  errno: 'EPIPE',
  syscall: 'write',
  source: 'socket' }
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:848:14)
    at Immediate._onImmediate (_stream_wrap.js:147:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)
Loading config...
--end snippet---

this continues to cycle.

IMAP settings for office 365:
Incoming: IMAP
Server hostname: outlook.office365.com
Port: 993
SSL: SSL/TLS

thanks

Neil

**Comment by GunbotKitty** [comment]
Closing due to inactivity. Open a new issue if necessary.
