### ISSUE TITLE
Gunbot  MacOS Error

### ISSUE THREAD

**Issue by realbabymark** [GuntharDeNiro/BTCT#442]
Getting this error everytime I run gunthy. 

Loading config...
Loading exchange - binance
Unhandled rejection TypeError: Cannot read property 'indicators' of undefined
    at Object.<anonymous> (/snapshot/gunbot/tulind/index.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1226:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at Module.require (pkg/prelude/bootstrap.js:1136:31)
    at require (internal/module.js:11:18)
    at __dirname (/snapshot/gunbot/gain.js:0:0)
    at Object.<anonymous> (/snapshot/gunbot/gain.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1226:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at Module.require (pkg/prelude/bootstrap.js:1136:31)
    at require (internal/module.js:11:18)
    at module.exports (/snapshot/gunbot/requirefix.js:0:0)
    at _.forEach.Promise.then (/snapshot/gunbot/bot.lib.js:0:0)
    at tryCatcher (/snapshot/gunbot/node_modules/bluebird/js/release/util.js:16:23)

**Comment by BigB117** [comment]
I too am having this exact same issue trying to get Kraken going on my MacOS.

Someone please help!
