### ISSUE TITLE
V 8.0.3 Mac issue unhandler error.... PC version saying my license is Invalid

### ISSUE THREAD

**Issue by emotionlesstrader** [GuntharDeNiro/BTCT#456]
I noticed that in the zip file its no longer:

gunthy-gui-macos   its gunthy-gui

when I run on the MAC, where the old version worked, the new version throws an error:
JohnnysnsterPro:Gunbot XT Edition - MacOs packageV8 Brain2$ ./gunthy-gui
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::5000
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server.setupListenHandle [as _listen2] (net.js:1305:14)
    at listenInCluster (net.js:1353:12)
    at Server.listen (net.js:1453:7)
    at Application.listen (/snapshot/gunbot-autoconfig/node_modules/koa/lib/application.js:64:19)
    at Object.<anonymous> (/snapshot/gunbot-autoconfig/index.js:21:5)
    at Module._compile (pkg/prelude/bootstrap.js:1226:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1281:12)
    at startup (bootstrap_node.js:200:16)
    at bootstrap_node.js:617:3

Now on the PC Windows 10 when I run the new version8.0.3 its telling me that my License is not valid. The old version is working.

I did copy the db.sqlite into the directory as requested..

Any ideas?  Thanks in Advance!!

**Comment by emotionlesstrader** [comment]
Make sure to reboot your machine!!!! that was the issue....
