### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by pacstratllc** [GuntharDeNiro/BTCT#48]
Hi all,

I keep getting an error message 403.  Can I get some assistance in fixing this?  Here's the code:

Creating market client for BTC_FCT pair
Activating hot reconfig...
###[ --2017/08/25 18:37:44--poloniex--BTC_FCT  --  Gunbot v3.3 cycle #1 --------------- ]
::::: collecting market data...
Server running at http://127.0.0.1:63659
(node:21876) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
Unhandled rejection Error: statusCode 403
    at Object.console.C:\snapshot\Users\Enrico\Desktop\xBot_v2.9.3\poloniex.js.module.exports.Market.getLastBuyRate.poloniex.returnTradeHistory [as callback] (evalmachine.<anonymous>:0:0)
    at C:\snapshot\Users\Enrico\Desktop\xBot_v2.9.3\node_modules\async\dist\async.js:2243:31
    at C:\snapshot\Users\Enrico\Desktop\xBot_v2.9.3\node_modules\async\dist\async.js:906:16
    at Request._callback (C:\snapshot\Users\Enrico\Desktop\xBot_v2.9.3\node_modules\plnx\lib\index.js:134:7)
    at Request.self.callback (C:\snapshot\Users\Enrico\Desktop\xBot_v2.9.3\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:192:7)
    at Request.<anonymous> (C:\snapshot\Users\Enrico\Desktop\xBot_v2.9.3\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:189:7)
    at IncomingMessage.<anonymous> (C:\snapshot\Users\Enrico\Desktop\xBot_v2.9.3\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:291:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Unhandled rejection Error: statusCode 403
    at Object.console.C:\snapshot\Users\Enrico\Desktop\xBot_v2.9.3\poloniex.js.module.exports.Market.getLastBuyRate.poloniex.returnTradeHistory [as callback] (evalmachine.<anonymous>:0:0)
    at C:\snapshot\Users\Enrico\Desktop\xBot_v2.9.3\node_modules\async\dist\async.js:2243:31
    at C:\snapshot\Users\Enrico\Desktop\xBot_v2.9.3\node_modules\async\dist\async.js:906:16
    at Request._callback (C:\snapshot\Users\Enrico\Desktop\xBot_v2.9.3\node_modules\plnx\lib\index.js:134:7)
    at Request.self.callback (C:\snapshot\Users\Enrico\Desktop\xBot_v2.9.3\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:192:7)
    at Request.<anonymous> (C:\snapshot\Users\Enrico\Desktop\xBot_v2.9.3\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:189:7)
    at IncomingMessage.<anonymous> (C:\snapshot\Users\Enrico\Desktop\xBot_v2.9.3\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:291:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
***************************************************
EMA1:0.00652395 - EMA2:0.00645322
***************************************************
Unhandled rejection Error: statusCode 403
    at Object.console.C:\snapshot\Users\Enrico\Desktop\xBot_v2.9.3\poloniex.js.module.exports.Market.getLastBuyRate.poloniex.returnTradeHistory [as callback] (evalmachine.<anonymous>:0:0)
    at C:\snapshot\Users\Enrico\Desktop\xBot_v2.9.3\node_modules\async\dist\async.js:2243:31
    at C:\snapshot\Users\Enrico\Desktop\xBot_v2.9.3\node_modules\async\dist\async.js:906:16
    at Request._callback (C:\snapshot\Users\Enrico\Desktop\xBot_v2.9.3\node_modules\plnx\lib\index.js:134:7)
    at Request.self.callback (C:\snapshot\Users\Enrico\Desktop\xBot_v2.9.3\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:192:7)
    at Request.<anonymous> (C:\snapshot\Users\Enrico\Desktop\xBot_v2.9.3\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:189:7)
    at IncomingMessage.<anonymous> (C:\snapshot\Users\Enrico\Desktop\xBot_v2.9.3\node_modules\request\request.js:1091:12)
    at Object.onceWrapper (events.js:291:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
++2017/08/25 18:37:45 Error: statusCode 403
!!! Cycle 2 failed. Will repeat in 60s

**Comment by GuntharDeNiro** [comment]
403 error is coming directly from poloniex: bad credentials. 
Check api/secret and/or ip restriction and/or if you are using gunbot from one of the banned countires or ip range from poloniex.

**Comment by Singman33** [comment]
Or a better solution, upgrade to v4.0.5 and you will get a better experience. Really.
