### ISSUE TITLE
v8 crashing after some time

### ISSUE THREAD

**Issue by kataoki1** [GuntharDeNiro/BTCT#481]
my bot keeps crashing after some time, sometimes 15 mins-4 hours+
i keep receiving this error
TypeError: Cannot read property 'Available' of undefined
    at module.exports.parseBalance._.forEach (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
    at arrayEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537:11)
    at Function.forEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:9359:14)
    at Bittrex.parseBalance (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
    at C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0
    at Request._callback (C:\snapshot\Gunbot-master\node_modules\node-bittrex-api\node.bittrex.api.js:144:11)
    at Request.init.self.callback (C:\snapshot\Gunbot-master\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537
      if (iteratee(array[index], index, array) === false) {
          ^

**Comment by jhoijtink** [comment]
Yeah mine does this as well. I have to restart the bot couple times a day...

**Comment by theGreatestBeansOnEarth** [comment]
same happens to me. Don't know what's causing it

**Comment by jhoijtink** [comment]
I went back to v7, works better for me

**Comment by kamushadenes** [comment]
Same issue =/

**Comment by Steempunker** [comment]
Same for me, this needs to be fixed as a priority. As it stops trading completely and you loose money !!!
