### ISSUE TITLE
v803 random config reload

### ISSUE THREAD

**Issue by miwi-fbsd** [GuntharDeNiro/BTCT#486]
I saw this on 3 bots with bittrex, config reloads suddenly and out of nowhere with following error..

This error is with debug on and -vvv
Anyone any idea what the cause is and how to workaround that?

```
All good...keep calm and Gunbot.
GBXT_v8.0.3 BTC-ABY Round # 1
------------------------------------------------------------------------------------------------
 ɢՍΠƁʘŦ XT Edition  Scanning bittrex for trading opportunities 2018/02/03 07:43:55
------------------------------------------------------------------------------------------------
Last trade P/L for BTC-ABY was: 0.000 %
All good...keep calm and Gunbot.
GBXT_v8.0.3 BTC-AEON Round # 1
------------------------------------------------------------------------------------------------
 ɢՍŋƁ๏ͳ XT Edition  Scanning bittrex for trading opportunities 2018/02/03 07:44:01
------------------------------------------------------------------------------------------------
/snapshot/Gunbot-master/node_modules/lodash/lodash.js:537
      if (iteratee(array[index], index, array) === false) {
          ^

TypeError: Cannot read property 'Available' of undefined
    at module.exports.parseBalance._.forEach (/snapshot/Gunbot-master/ctx/js/bittrex.js:0:0)
    at arrayEach (/snapshot/Gunbot-master/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/snapshot/Gunbot-master/node_modules/lodash/lodash.js:9359:14)
    at Bittrex.parseBalance (/snapshot/Gunbot-master/ctx/js/bittrex.js:0:0)
    at /snapshot/Gunbot-master/ctx/js/bittrex.js:0:0
    at Request._callback (/snapshot/Gunbot-master/node_modules/node-bittrex-api/node.bittrex.api.js:144:11)
    at Request.init.self.callback (/snapshot/Gunbot-master/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/snapshot/Gunbot-master/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/snapshot/Gunbot-master/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Loading config...
Loading exchange - bittrex
GBXT_v8.0.3 BTC-2GIVE Round # 1
------------------------------------------------------------------------------------------------
 ɢƱҊƁѺŁ XT Edition  Scanning bittrex for trading opportunities 2018/02/03 07:44:04
------------------------------------------------------------------------------------------------
/snapshot/Gunbot-master/node_modules/lodash/lodash.js:537
      if (iteratee(array[index], index, array) === false) {
          ^

TypeError: Cannot read property 'Available' of undefined
    at module.exports.parseBalance._.forEach (/snapshot/Gunbot-master/ctx/js/bittrex.js:0:0)
    at arrayEach (/snapshot/Gunbot-master/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/snapshot/Gunbot-master/node_modules/lodash/lodash.js:9359:14)
    at Bittrex.parseBalance (/snapshot/Gunbot-master/ctx/js/bittrex.js:0:0)
    at /snapshot/Gunbot-master/ctx/js/bittrex.js:0:0
    at Request._callback (/snapshot/Gunbot-master/node_modules/node-bittrex-api/node.bittrex.api.js:144:11)
    at Request.init.self.callback (/snapshot/Gunbot-master/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/snapshot/Gunbot-master/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/snapshot/Gunbot-master/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Loading config...
Loading exchange - bittrex
GBXT_v8.0.3 BTC-2GIVE Round # 1
------------------------------------------------------------------------------------------------
 ɢƱͶ฿ǾŁ XT Edition  Scanning bittrex for trading opportunities 2018/02/03 07:44:08
------------------------------------------------------------------------------------------------
/snapshot/Gunbot-master/node_modules/lodash/lodash.js:537
      if (iteratee(array[index], index, array) === false) {
          ^

TypeError: Cannot read property 'Available' of undefined
    at module.exports.parseBalance._.forEach (/snapshot/Gunbot-master/ctx/js/bittrex.js:0:0)
    at arrayEach (/snapshot/Gunbot-master/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/snapshot/Gunbot-master/node_modules/lodash/lodash.js:9359:14)
    at Bittrex.parseBalance (/snapshot/Gunbot-master/ctx/js/bittrex.js:0:0)
    at /snapshot/Gunbot-master/ctx/js/bittrex.js:0:0
    at Request._callback (/snapshot/Gunbot-master/node_modules/node-bittrex-api/node.bittrex.api.js:144:11)
    at Request.init.self.callback (/snapshot/Gunbot-master/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/snapshot/Gunbot-master/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/snapshot/Gunbot-master/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Loading config...
Loading exchange - bittrex
GBXT_v8.0.3 BTC-2GIVE Round # 1
------------------------------------------------------------------------------------------------
 ɢՍͶβ๏Ł XT Edition  Scanning bittrex for trading opportunities 2018/02/03 07:44:11
------------------------------------------------------------------------------------------------
Last trade P/L for BTC-2GIVE was: 0.000 %
All good...keep calm and Gunbot.
GBXT_v8.0.3 BTC-ABY Round # 1
------------------------------------------------------------------------------------------------
 ɢՍÑɮ๏Ł XT Edition  Scanning bittrex for trading opportunities 2018/02/03 07:44:16
------------------------------------------------------------------------------------------------
Last trade P/L for BTC-ABY was: 0.000 %
All good...keep calm and Gunbot.
GBXT_v8.0.3 BTC-AEON Round # 1
------------------------------------------------------------------------------------------------
 ɢƱΠβʘŁ XT Edition  Scanning bittrex for trading opportunities 2018/02/03 07:44:22
------------------------------------------------------------------------------------------------
/snapshot/Gunbot-master/node_modules/lodash/lodash.js:537
      if (iteratee(array[index], index, array) === false) {
          ^

TypeError: Cannot read property 'Available' of undefined
    at module.exports.parseBalance._.forEach (/snapshot/Gunbot-master/ctx/js/bittrex.js:0:0)
    at arrayEach (/snapshot/Gunbot-master/node_modules/lodash/lodash.js:537:11)
    at Function.forEach (/snapshot/Gunbot-master/node_modules/lodash/lodash.js:9359:14)
    at Bittrex.parseBalance (/snapshot/Gunbot-master/ctx/js/bittrex.js:0:0)
    at /snapshot/Gunbot-master/ctx/js/bittrex.js:0:0
    at Request._callback (/snapshot/Gunbot-master/node_modules/node-bittrex-api/node.bittrex.api.js:144:11)
    at Request.init.self.callback (/snapshot/Gunbot-master/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/snapshot/Gunbot-master/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/snapshot/Gunbot-master/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
Loading config...
Loading exchange - bittrex
GBXT_v8.0.3 BTC-2GIVE Round # 1
```

**Comment by Steempunker** [comment]
I have the same problem, which is on another thread along with a few others

**Comment by BigB117** [comment]
I too have the same problem on Bittrex with 8.0.3 on a Windows Server.

Where's the solution??
