### ISSUE TITLE
Gunbot popup claiming Sold xx @ Price 0.xxx , followed by popup Amount:0 Price:0

### ISSUE THREAD

**Issue by derCel** [GuntharDeNiro/BTCT#499]
Hi all,

**System & Settings -** 

Version: 8.0.3
Platform: Windows 10
Exchange: kraken
Pairs: BTC-ETH, BTC-REP, GNO-ETH
Strategy: bb

All currencies provided in sufficient amount to start with.

changed following strategy settings, everything else default:
TRADING_LIMIT 0.002
MIN VOLUME TO BUY/SELL: 0.001
OKKIES_MODE: false

**Issue -** 

I am using this bot on kraken.com with BTC-ETH pairing testing the bbstepgain strategy.
Whenever gunbot identifies a good selling opportunity it acts as if it would sell x amount for x price followed by another popup saying Sold amount: 0 Price: 0

![gunbot_small](https://user-images.githubusercontent.com/36377014/36075939-bdd48026-0f55-11e8-91dc-0a2b7873ae1b.jpg)

kraken API has all rights except for withdrawal tried both only using master API key and with an additonal API key for trading. 

Thanks,
Cel

**Comment by kendoll30** [comment]
Exactly the same for me on BTC-XRP ... 
But TRADING_LIMIT to 0.1 isn't it to much?
I am using emotionless and i have 0.001

**Comment by kendoll30** [comment]
In fact do you have a list of actually working pairs on Kraken? For me it worked just with Ripple and BTC.
Do you have to make an initial manual transaction with Dash for example before Gunbot is able to work with further or you can initiate new pairs as long as you have BTC in stock?

**Comment by derCel** [comment]
Pairs I'm trying on kraken: BTC-ETH, BTC-REP, GNO-ETH
None of these work at the moment though.

I provided a small amount of both pair currencies for the bot to start with - not sure this is needed.

while checking the debug logs I found the following:
Bid is bad or Altcoin balance is bad: true
Ask is bad or Base balance is bad: true

These warnings came for BTC-REP this morning. Maybe TRADING_LIMIT might cause the issue so I lowered it to 0.002 as you suggested to give it a try.

**Comment by kendoll30** [comment]
![error](https://user-images.githubusercontent.com/36370293/36087862-cb4e4cc6-0fd4-11e8-924f-adfd51ebfed5.jpg)

This is so frustrating.....

**Comment by derCel** [comment]
Here's the newest error message I get - 

Now I receive the following error messages for all pairs - 

Error: "Fetching balance again."
    at errorHandler (C:\snapshot\Gunbot-master\ctx-wrapper.js:0:0)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Error: "Fetching my trades again."
    at errorHandler (C:\snapshot\Gunbot-master\ctx-wrapper.js:0:0)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Error: "Fetching open orders again."
    at errorHandler (C:\snapshot\Gunbot-master\ctx-wrapper.js:0:0)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Retstarted the bot now. Still waiting for a new order to trigger though.

**Comment by derCel** [comment]
@kendoll30 

I was wondering, since you got at least Ripple/BTC working, did you start with funds for both Ripple and BTC? I deposited approx. 200 EUR per Altcoin now and some more for my mains BTC & ETH. Let's see if that does the trick. Just need to enter a buy/sell cycle now ... the action always seems to happen while I'm asleep. ;)

Thanks!

**Comment by kendoll30** [comment]
I started initially with EUR (without bot) then bought XRP (without bot) then transfered everything to BTC (still without bot) and then started just BTC-XRP .. it buys but doesn't sell back :(

**Comment by derCel** [comment]
Hmm. I'm out of ideas. I also checked the forum and github extensively for information on this issue but couldn't find anything related. I'm glad however, that I'm not the only one experiencing this issue (sorry!). Now all we need is a pointer in the right direction. 

@GuntharDeNiro - please help us

**Comment by derCel** [comment]
@kendoll30 

I found the following thread on gunthy.org which suggests to increase the bot delay to 10 specifically for kraken as it seems to be the slowest exchange there is.

I cannot confirm yet since no trade happened so far but thought it would be helpful to you nevertheless.

https://gunthy.org/forum/index.php?topic=2103.0

**Comment by cryptometal** [comment]
Have the same issue on Bittrex. Increasing bot delay to 25 didn't help.

**Comment by davepro305** [comment]
Did you guys find the reason? I'm having the same problem on Binance
