### ISSUE TITLE
Gunbot restarts 100's of times a day...

### ISSUE THREAD

**Issue by storxusmc** [GuntharDeNiro/BTCT#518]
i setup the new version of gunbot on a handful of pairs, run the bot and it keeps erroring and restarting, really never getting past like 30+ rounds before restarting again...

TypeError: Cannot read property 'Available' of undefined
    at module.exports.parseBalance._.forEach (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
    at arrayEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537:11)
    at Function.forEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:9359:14)
    at Bittrex.parseBalance (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
    at C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0
    at Request._callback (C:\snapshot\Gunbot-master\node_modules\node-bittrex-api\node.bittrex.api.js:144:11)
    at Request.init.self.callback (C:\snapshot\Gunbot-master\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537
      if (iteratee(array[index], index, array) === false) {
          ^

TypeError: Cannot read property 'Available' of undefined
    at module.exports.parseBalance._.forEach (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
    at arrayEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:537:11)
    at Function.forEach (C:\snapshot\Gunbot-master\node_modules\lodash\lodash.js:9359:14)
    at Bittrex.parseBalance (C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0)
    at C:\snapshot\Gunbot-master\ctx\js\bittrex.js:0:0
    at Request._callback (C:\snapshot\Gunbot-master\node_modules\node-bittrex-api\node.bittrex.api.js:144:11)
    at Request.init.self.callback (C:\snapshot\Gunbot-master\node_modules\request\request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage. (C:\snapshot\Gunbot-master\node_modules\request\request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by ludalex** [comment]
Happening the same to me as well.
