### ISSUE TITLE
Getting many 422 errors on just 8 pairs

### ISSUE THREAD

**Issue by utdrmac** [GuntharDeNiro/BTCT#6]
Upgraded to 3.3.2 today. Still getting many 422 on just 8 pairs, all same API key.

Sometimes the error looks like this:

```
Unhandled rejection Error: statusCode 422
    at Object.console./snapshot/Users/Enrico/Desktop/xBot_v2.9.3/poloniex.js.module.exports.Market.checkifwesold.poloniex.returnOpenOrders [as callback] (evalmachine.<anonymous>:0:0)
    at /snapshot/Users/Enrico/Desktop/xBot_v2.9.3/node_modules/async/dist/async.js:2243:31
    at /snapshot/Users/Enrico/Desktop/xBot_v2.9.3/node_modules/async/dist/async.js:906:16
    at Request._callback (/snapshot/Users/Enrico/Desktop/xBot_v2.9.3/node_modules/plnx/lib/index.js:134:7)
    at Request.self.callback (/snapshot/Users/Enrico/Desktop/xBot_v2.9.3/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:192:7)
    at Request.<anonymous> (/snapshot/Users/Enrico/Desktop/xBot_v2.9.3/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:189:7)
    at IncomingMessage.<anonymous> (/snapshot/Users/Enrico/Desktop/xBot_v2.9.3/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:291:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

sometimes it looks like this

```
BB price to sell 0.018854729 -- GAIN price to sell 0
BB price to buy 0.01861997242526518 -- GAIN price to buy 0.018175230298823526
+++2017/07/06 13:21:15 Error: statusCode 422
!!! Cycle 109 failed. Will repeat in 87.97918456982607s
```

Perhaps storing the current nonce in a local .txt file and each instance reading the most recent value out of this file in order to synchronize API calls?

**Comment by utdrmac** [comment]
Solution here is to, unfortunately, run the community proxy. Seems to be the accepted solution.

**Comment by MahirZukic** [comment]
What do you mean by community proxy?

**Comment by cryptowally** [comment]
There's a community proxy available at
https://github.com/taniman/gunbotproxycommunity/releases that acts as a
man-in-the-middle and performs caching for poloniex and eliminates the 422
and 429 errors of gunbot versions 3.3.2 and earlier.  In short, the
community proxy replaces all gunbot communication to poloniex and connects
to poloniex on regular intervals - say, every 3-5 seconds.  So, instead of
each gunbot instance connecting to poloniex independently for each API
call, the gunbot instance ends up connecting to the proxy and is able to
get the cached pricing information.

It works well.
