### ISSUE TITLE
Error: Token expired

### ISSUE THREAD

**Issue by pjlwealth** [GuntharDeNiro/BTCT#649]
Received this error tonight, workaround was to clear the cache of my browser.

Everytime i refreshed the GUI, the error was logged. but gunbot was still running on the background doing its magic.

Some how the 2FA token or ?https token? expired or something.
Can we have gunbot logout the session if this error appears, forcing a relog?

Ill leave my gunbot session open, see if it occurred again.

0|gunthy-l | Error: Token expired
0|gunthy-l |     at Object.jwt_decode [as decode] (/snapshot/Gunbot-master/gui/node_modules/jwt-simple/lib/jwt.js:92:13)
0|gunthy-l |     at Object.decodeToken (/snapshot/Gunbot-master/gui/localAuth.js:0:0)

![screen shot 2018-10-08 at 9 20 24 pm](https://user-images.githubusercontent.com/31854775/46641520-0c545900-cb40-11e8-9fa2-65fe2f4b11b9.png)

**Comment by pjlwealth** [comment]
My Bad, Just read there was a new Build, that fixed token expiration.
Closing this.

Gunthar De Niro, [08.10.18 13:30]
Gunbot v10.7.2 (Build 837) - Stable release

Gunthar De Niro, [08.10.18 13:30]
**- Fix token expiration**
-Fix PV charts causing lag due to large number of records in db table
-Automatically set BOUGHT_PRICE to null if an ABP is reliably available from exchange: avoid the user to have to delete BOUGHT_PRICE when the 30 days history has become obsolete.
-Fixed BUY order for TV plugin
-Move ichimoku logs at the end of the grid to help log parsers
-Tuning all indicators to get closer to TV values
-Alerting the user to wait one more cycle before to override a BOUGHT_PRICE if the cause is an empty API response
-Mitigating Poloniex statuscode 422 error
-Mitigating error 520 Origin at Kraken
-Increase Bitfinex nonce
-Fix telegram message
-Fix Pair locked funds
-Fix EMF too many files open and EBADF error
