### ISSUE TITLE
Averaging down leads to error

### ISSUE THREAD

**Issue by dfischer** [GuntharDeNiro/BTCT#670]
```
AVERAGING DOWN!!!
The value of this coin dropped below bought price (0.00010955641604010026). Proceeding with DU!
Error: {}
    at errorHandler (/snapshot/gunbotv11public/ctx-wrapper.js:0:0)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Version: 11.7

**Comment by the-scott-davis** [comment]
Yeah I’m getting this too on multiple pairs. I had to disable them to get the error to stop. I restarted on of the pairs hours later after the price came up and it was fine after that.

**Comment by lord-roachington** [comment]
I had this problem before but it was actually because my double up buys were smaller then my min order to buy, Once I worked out the correct amounts it worked again.

**Comment by dfischer** [comment]
Got it, same conclusion. Should properly error in the server though.

**Comment by GunbotKitty** [comment]
Closing due to inactivity. Open a new issue if necessary.
