### ISSUE TITLE
Imap timeouts

### ISSUE THREAD

**Issue by FredFoo** [GuntharDeNiro/BTCT#675]
I was configuring gunbot TradingView Edition v11.7.6 Build 906.

When I enable the Imap Listener and start the bot I sometimes get timeouts first. After a few - or many - tries finally it works. When I enable TLS timeouts happen more frequently. If I also enable Telegram I was never able to see a valid connection with the Imap server. Interenstingly while the Imap server thinks everything is just fine and responds really quick.

It seems from the logs the timeout is about 5 seconds. So I dont think that is actually the root cause. The machine does not show a high load, the connection is a 1GB and ping times are great. 
 
Any idea how to investigate this further?

```
Dec  1 10:34:06 gunbot-a1 gunthy-linx64[24706]: { Error: Timed out while authenticating with server
Dec  1 10:34:06 gunbot-a1 gunthy-linx64[24706]:     at Timeout._onTimeout (/snapshot/gunbotv11public/node_modules/imap/lib/Connection.js:139:17)
Dec  1 10:34:06 gunbot-a1 gunthy-linx64[24706]:     at ontimeout (timers.js:478:11)
Dec  1 10:34:06 gunbot-a1 gunthy-linx64[24706]:     at tryOnTimeout (timers.js:302:5)
Dec  1 10:34:06 gunbot-a1 gunthy-linx64[24706]:     at Timer.listOnTimeout (timers.js:262:5) source: 'timeout-auth' }
```

**Comment by GunbotKitty** [comment]
Closing due to inactivity. Open a new issue if necessary.
