### ISSUE TITLE
Telegram module crashing the bot

### ISSUE THREAD

**Issue by Paddy888** [GuntharDeNiro/BTCT#687]
GBRT_v12.8.9 on Ubuntu 16.04

I have Telegram set to false, but the bot is still trying to send messages and crashing. Can't even restart it. I have tried editing the config and set all notifications to false as well. Just keeps crashing.

The path to these files in the error message does not match my environment at all. I do not recognize it.

TypeError: Cannot   read property 'message_id' of undefined
--
at module.exports.sendConfirmActionOrder.actions.send.then   (/snapshot/gblackv12/telegram.js:0:0)
at tryCatcher   (/snapshot/gblackv12/node_modules/bluebird/js/release/util.js:16:23)
at Promise.module.exports.Promise._settlePromiseFromHandler   (/snapshot/gblackv12/node_modules/bluebird/js/release/promise.js:512:31)
at Promise.module.exports.Promise._settlePromise   (/snapshot/gblackv12/node_modules/bluebird/js/release/promise.js:569:18)
at Promise.module.exports.Promise._settlePromiseCtx   (/snapshot/gblackv12/node_modules/bluebird/js/release/promise.js:606:10)
at _drainQueueStep   (/snapshot/gblackv12/node_modules/bluebird/js/release/async.js:142:12)
at _drainQueue   (/snapshot/gblackv12/node_modules/bluebird/js/release/async.js:131:9)
at Async._drainQueues   (/snapshot/gblackv12/node_modules/bluebird/js/release/async.js:147:5)
at Immediate.__dirname.Async.drainQueues [as _onImmediate]   (/snapshot/gblackv12/node_modules/bluebird/js/release/async.js:17:14)
at runCallback (timers.js:800:20)
at tryOnImmediate (timers.js:762:5)
at processImmediate [as _immediateCallback] (timers.js:733:5)   'Unhandled Rejection at Promise' Promise {
_bitField: 18087936,
_fulfillmentHandler0: TypeError: Cannot read property 'message_id' of   undefined
at module.exports.sendConfirmActionOrder.actions.send.then   (/snapshot/gblackv12/telegram.js:0:0)
at tryCatcher   (/snapshot/gblackv12/node_modules/bluebird/js/release/util.js:16:23)
at Promise.module.exports.Promise._settlePromiseFromHandler   (/snapshot/gblackv12/node_modules/bluebird/js/release/promise.js:512:31)
at Promise.module.exports.Promise._settlePromise   (/snapshot/gblackv12/node_modules/bluebird/js/release/promise.js:569:18)
at Promise.module.exports.Promise._settlePromiseCtx   (/snapshot/gblackv12/node_modules/bluebird/js/release/promise.js:606:10)
at _drainQueueStep   (/snapshot/gblackv12/node_modules/bluebird/js/release/async.js:142:12)
at _drainQueue   (/snapshot/gblackv12/node_modules/bluebird/js/release/async.js:131:9)
at Async._drainQueues   (/snapshot/gblackv12/node_modules/bluebird/js/release/async.js:147:5)
at Immediate.__dirname.Async.drainQueues [as _onImmediate]   (/snapshot/gblackv12/node_modules/bluebird/js/release/async.js:17:14)
at runCallback (timers.js:800:20)
at tryOnImmediate (timers.js:762:5)
at processImmediate [as _immediateCallback] (timers.js:733:5),
_rejectionHandler0: undefined,
_promise0: undefined,
_receiver0: undefined }

**Comment by Paddy888** [comment]
I solved this by turning telegram notifications on. Seems to be a bug
