### ISSUE TITLE
TypeError: Parse buffer must be String or Buffer

### ISSUE THREAD

**Issue by codepushr** [GuntharDeNiro/BTCT#703]
Experiencing this crash on my Ubuntu 16.0 instance after some time.
Any ideas why and how to fix?

v12.8.9

```Loading config...
info: socket.io started
GUI Server Deployed: http://localhost:5000
TypeError: Parse buffer must be String or Buffer
    at Parser.parse (/snapshot/gblackv12/node_modules/node-expat/lib/node-expat.js:23:22)
    at Object.module.exports [as toJson] (/snapshot/gblackv12/node_modules/xml2json/lib/xml2json.js:172:17)
    at Request._callback (/snapshot/gblackv12/bot.gunbot.js:0:0)
    at Request.init.self.callback (/snapshot/gblackv12/node_modules/request/request.js:185:22)
    at Request.emit (events.js:159:13)
    at Request.onRequestError (/snapshot/gblackv12/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:159:13)
    at Socket.socketErrorListener (_http_client.js:389:9)
    at Socket.emit (events.js:159:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) 'Uncaught Exception thrown'
```

**Comment by grumpy-kitty** [comment]
Please update to v12.9.9 and test whether this happens.
