### ISSUE TITLE
404 StatusCodeError on trying to Update Registered Master Key

### ISSUE THREAD

**Issue by spikything** [GuntharDeNiro/BTCT#709]
v12.9.2 When attempting to Update Registered Master Key (necessary since Binance deleted all API keys after their recent security breach), an error is thrown and Gunbot restarts - http://api.gunthy.org:5000/updateMasterKey is not found (tried from different IP addresses at different times):

```
StatusCodeError: 404 - "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST /updateMasterKey</pre>\n</body>\n</html>\n"
    at new StatusCodeError (C:\snapshot\gunbotv12_alfa\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.module.exports.plumbing.callback (C:\snapshot\gunbotv12_alfa\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (C:\snapshot\gunbotv12_alfa\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.init.self.callback (C:\snapshot\gunbotv12_alfa\node_modules\request\request.js:185:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (C:\snapshot\gunbotv12_alfa\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (C:\snapshot\gunbotv12_alfa\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'StatusCodeError',
  statusCode: 404,
  message: '404 - "<!DOCTYPE html>\\n<html lang=\\"en\\">\\n<head>\\n<meta charset=\\"utf-8\\">\\n<title>Error</title>\\n</head>\\n<body>\\n<pre>Cannot POST /updateMasterKey</pre>\\n</body>\\n</html>\\n"',
  error: '<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST /updateMasterKey</pre>\n</body>\n</html>\n',
  options:
   { uri: 'http://api.gunthy.org:5000/updateMasterKey',
     method: 'POST',
     body: '...
```

**Comment by grumpy-kitty** [comment]
Please update to the latest build: https://github.com/GuntharDeNiro/BTCT/releases/tag/1299.

**Comment by spikything** [comment]
> Please update to the latest build: https://github.com/GuntharDeNiro/BTCT/releases/tag/1299.

The "Update Registered Master Key" UI component only appears for a Gunbot instance which believes it is licensed (where the Swap Exchanges tab shows a license). Since Binance deleted all API keys, a new Gunbot installation does not show that component after GUNTHY wallet and Binance keys are added. I have no knowledge of the inner workings of the license server, but also assume that, if it checks that the registered master key and new key belong to the same account, this will fail for all previously Binance registered keys.

I have contacted my reseller about moving keys, but he is unresponsive.
