### ISSUE TITLE
Leveraged orders in bitfinex do not close correctly

### ISSUE THREAD

**Issue by CRYPTONIKAV** [GuntharDeNiro/BTCT#739]
GBT: 12.9.9.2

Stage
When we have a LONG order leveraged in bitfinex and the closing command is sent (CLOSELONG_BITFINEX_USD-LTC) the error shown below appears.

Error:
emailParsed { timestamp: 1562623264447,
  type: 'closelong',
  exchange: 'bitfinex',
  pair: 'USD-LTC',
  tl: '25' }

2019/07/08 18:01:04: Checking prices...
2019/07/08 18:01:05: Received a CLOSE order...

product-info { minTradeAmt: 0.04, minPrice: 0.00001 }
Original price: 121.18
Original volume: 0
Rounded price: 121.18
Rounded volume: 0
{"message":"Minimum volume must be: 0.04. You tried 0"}
Error: {"message":"Minimum volume must be: 0.04. You tried 0"}
    at errorHandler (C:\snapshot\gblackv12\ctx\js\bitfinex.js:0:0)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Action performed:
- It was opened with LONG_BITFINEX_USD-LTC_50
- Attempt to close with CLOSELONG_BITFINEX_USD-LTC
- Attempt to close with CLOSELONG_BITFINEX_USD-LTC_50

**Comment by Dante2333** [comment]
Could it be that its so low that now its below Bitfinex threshold? Can you include more logs please?

**Comment by CRYPTONIKAV** [comment]
I have done tests with different amounts, from $150 leveraged up to $25. The funds were in the MARGIN wallet in USD.

In all cases, that error appears.
