### ISSUE TITLE
Cannot read property 'liquidationPrice' of undefined on BitMex

### ISSUE THREAD

**Issue by CRYPTONIKAV** [GuntharDeNiro/BTCT#740]
GBT 12.9.9.2

This error appears randomly in the trading pairs: 
(XBT-USD, ETH-USD, LTC-U19, EOS-U19, XRP-U19)

TypeError: Cannot read property 'liquidationPrice' of undefined
    at module.exports.Strategy.process.Promise.try.then.Promise.memory.exchanges.(anonymous function).getBalances (C:\snapshot\gblackv12\gain.js:0:0)
    at module.exports.Market.getBalances.Promise.checkSecurity.then.that.exchangeController.fetchBalance.then.data (C:\snapshot\gblackv12\ctx-wrapper.js:0:0)
    at tryCatcher (C:\snapshot\gblackv12\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.module.exports.Promise._settlePromiseFromHandler (C:\snapshot\gblackv12\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise.module.exports.Promise._settlePromise (C:\snapshot\gblackv12\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise.module.exports.Promise._settlePromise0 (C:\snapshot\gblackv12\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise.module.exports.Promise._settlePromises (C:\snapshot\gblackv12\node_modules\bluebird\js\release\promise.js:694:18)
    at Promise.module.exports.Promise._fulfill (C:\snapshot\gblackv12\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise.module.exports.Promise._settlePromise (C:\snapshot\gblackv12\node_modules\bluebird\js\release\promise.js:582:21)
    at Promise.module.exports.Promise._settlePromise0 (C:\snapshot\gblackv12\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise.module.exports.Promise._settlePromises (C:\snapshot\gblackv12\node_modules\bluebird\js\release\promise.js:694:18)
    at Promise.module.exports.Promise._fulfill (C:\snapshot\gblackv12\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise.module.exports.Promise._resolveCallback (C:\snapshot\gblackv12\node_modules\bluebird\js\release\promise.js:432:57)
    at Promise.module.exports.Promise._settlePromiseFromHandler (C:\snapshot\gblackv12\node_modules\bluebird\js\release\promise.js:524:17)
    at Promise.module.exports.Promise._settlePromise (C:\snapshot\gblackv12\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise.module.exports.Promise._settlePromise0 (C:\snapshot\gblackv12\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise.module.exports.Promise._settlePromises (C:\snapshot\gblackv12\node_modules\bluebird\js\release\promise.js:694:18)
    at Promise.module.exports.Promise._fulfill (C:\snapshot\gblackv12\node_modules\bluebird\js\release\promise.js:638:18)
    at PromiseArray.module.exports.PromiseArray._resolve (C:\snapshot\gblackv12\node_modules\bluebird\js\release\promise_array.js:126:19)
    at PromiseArray.module.exports.PromiseArray._promiseFulfilled (C:\snapshot\gblackv12\node_modules\bluebird\js\release\promise_array.js:144:14)
    at Promise.module.exports.Promise._settlePromise (C:\snapshot\gblackv12\node_modules\bluebird\js\release\promise.js:574:26)
    at Promise.module.exports.Promise._settlePromise0 (C:\snapshot\gblackv12\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise.module.exports.Promise._settlePromises (C:\snapshot\gblackv12\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (C:\snapshot\gblackv12\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (C:\snapshot\gblackv12\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\snapshot\gblackv12\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.__dirname.Async.drainQueues [as _onImmediate] (C:\snapshot\gblackv12\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:800:20)

Action performed:
A 1: 1 contract is opened and closed to eliminate the error.

**Comment by CRYPTONIKAV** [comment]
GBT: 13.7.6 (beta)

![LIQP1](https://user-images.githubusercontent.com/29835619/62078521-ce353c80-b21a-11e9-8bec-05bb60e3dcc9.JPG)
Liquidation Price > undefined

![LIQP2](https://user-images.githubusercontent.com/29835619/62078602-fa50bd80-b21a-11e9-93be-965f5ff28015.JPG)

TypeError: Cannot read property 'liquidationPrice' of undefined
