### ISSUE TITLE
Gunbot does no trade with Kraken

### ISSUE THREAD

**Issue by akijuh** [GuntharDeNiro/BTCT#759]
Gunbot v.13 does no trade with Kraken, but prints only code l51000 when it should make a buy.
Exchange is Kraken and pair is EUR-ETH.
![photo_2019-09-18_14-25-21](https://user-images.githubusercontent.com/6022297/65144880-f07c5700-da20-11e9-993f-a7560cf01310.jpg)

**Comment by akijuh** [comment]
@GuntharDeNiro 

Gunbot v.14 still does not trade with Kraken, same old code l51000!

![gunbotv14](https://user-images.githubusercontent.com/6022297/66629292-fae9d500-ec09-11e9-92c7-3f5c8381c1b4.jpg)

**Comment by mattguetta** [comment]
Same here, did you find a way ?

```
0|gunthy-l | EUR-XRP@kraken checking buy conditions
0|gunthy-l |
0|gunthy-l | l51000
0|gunthy-l |
0|gunthy-l | EUR-XRP@kraken startingg rtbuy process
0|gunthy-l |
0|gunthy-l | entering rtbuy trade
0|gunthy-l | ɢՍҊɮǾŁ TradingView Edition -  Waiting for alerts...
0|gunthy-l | Error: Error: General:Invalid arguments:volume
0|gunthy-l |     at errorHandler (/snapshot/gblackv14/ctx/js/kraken.js:0:0)
0|gunthy-l |     at <anonymous>
0|gunthy-l |     at process._tickCallback (internal/process/next_tick.js:188:7)
0|gunthy-l |
0|gunthy-l | 2573
```

**Comment by akijuh** [comment]
> 
> 
> Same here, did you find a way ?
> 
No way until @GuntharDeNiro fix it.

**Comment by sgarcia159** [comment]
Last time I had and invalid arguments volume error. I was trying to place a
trade below the min order amount

**Comment by mattguetta** [comment]
I'll check that, thx! Would just be great to have an explicit message and not an error code ^^

**Comment by sgarcia159** [comment]
Just curious, so how'd it go?

**Comment by mattguetta** [comment]
Finally found it > wrong period used for Kraken.
> https://wiki.gunthy.org/how-to-work-with-gunbot/basic-workings/period#supported-period-values

**Comment by akijuh** [comment]
What you mean?
I have used standard 15 min indicator lenght, its not that.

**Comment by mattguetta** [comment]
Yes me too but depending on your EMA setting you can be on another candle analyse if I get it right

**Comment by akijuh** [comment]
> 
> 
> Yes me too but depending on your EMA setting you can be on another candle analyse if I get it right

So, did you get it working, if yes, could you show your settings?

**Comment by akijuh** [comment]
Tested GB in linux, sama thing, code l51000.

But in linux there is also info:
>>We reached max allowed RESERVE for this coin: please wait for some sell orders or change FUNDS_RESERVE

So i spent 8 hours to tweaking everything, and also FUNDS_RESERVE,
it does not matter what is in FUNDS_RESERVE setting, 0 or 0.0001 or 1, 
its always same thing when GB is trying to buy:

>>GBRT_14.9.2-RC BTC-TRX@binance Round #20 2019/12/04 18:15:32
>>l51000
>>We reached max allowed RESERVE for this coin: please wait for some sell orders or change FUNDS_RESERVE

I am losing my hope with GB, already lost4 months with this s***t.

**Comment by BrandonCopley** [comment]
I couldn't get it to ever really connect. Just gave up eventually. Any way
to return a license : P. It would connect and stay connected for 5 minutes,
Maybe I don't have this in me. but yeah, Kraken connection specifically
never worked for me. I tried for a long time, but couldn't get it to work.

**Comment by akijuh** [comment]
> 
> I couldn't get it to ever really connect. Just gave up eventually. Any way to return a license : P. It would connect and stay connected for 5 minutes, Maybe I don't have this in me. but yeah, Kraken connection specifically never worked for me. I tried for a long time, but couldn't get it to work.
> […](#)
Yes, i even created account to Binance, same thing with Binance, l51000 problem is bug, nothing to do with in exchange i'm sure.

**Comment by akijuh** [comment]
Ping to @GuntharDeNiro 
Is this problem known and are there plan to fix it?

**Comment by akijuh** [comment]
Guess what, v15.6.1 and same f***n l51000 !
