### ISSUE TITLE
Config will not load.

### ISSUE THREAD

**Issue by mikebussy3334** [GuntharDeNiro/BTCT#85]
blank unmodified config will not load, gives me this:

Loading config...
Bot crashed at 2017/09/11 10:02:24
Reason: Failed to load config!!!
Parameter: undefined
Original error: SyntaxError: Unexpected token } in JSON at position 389
    at JSON.parse (<anonymous>)
    at Promise (C:\snapshot\Gunbot-master\bot.js:0:0)
    at Promise.module.exports.Promise._execute (C:\snapshot\Gunbot-master\node_modules\bluebird\js\release\debuggability.js:300:9)
    at Promise.module.exports.Promise._resolveFromExecutor (C:\snapshot\Gunbot-master\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (C:\snapshot\Gunbot-master\node_modules\bluebird\js\release\promise.js:79:10)
    at loadConfig (C:\snapshot\Gunbot-master\bot.js:0:0)
    at Object.start (C:\snapshot\Gunbot-master\bot.js:0:0)
    at Object.<anonymous> (C:\snapshot\Gunbot-master\bot.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1173:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at Module.require (pkg/prelude/bootstrap.js:1083:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\snapshot\Gunbot-master\index.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1173:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
Loading config...

**Comment by pjlwealth** [comment]
Make sure to remove the comma in line 25

![screen shot 2017-09-10 at 8 51 17 pm](https://user-images.githubusercontent.com/31854775/30279267-c4a66b42-96da-11e7-84b8-f07cba37f6d1.png)


Else, copy paste the config in this site to validate the JSON format
http://jsonlint.com

**Comment by mikebussy3334** [comment]
You nailed it, Bro, thanks.
